"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "bn" | "brx" | "doi" | "gu" | "hi" | "kn" | "ks" | "gom" | "mai" | "ml" | "mni" | "mr" | "ne" | "or" | "pa" | "sa" | "sat" | "sd" | "ta" | "te" | "ur"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  translateCategory: (category: string) => string
  translateEvent: (eventId: string, field: 'title' | 'description', defaultValue: string) => string
  translateOrganizer: (organizerName: string) => string
  translateLocation: (location: string) => string
}

const translations = {
  en: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "hero.subtitle": "Unite Through Arts - Find Jatra, Cinema, Music, Dance & More",
    "stats.eventsBooked": "Events Booked",
    "stats.artists": "Registered Artists",
    "stats.tickets": "Tickets Sold",
    "stats.learners": "Active Learners",
    "stats.orders": "Custom Orders",
    "featured.title": "Featured Events",
    "featured.subtitle": "Handpicked arts and cultural experiences",
    "footer.discover": "Discover",
    "footer.browse": "Browse Events",
    "footer.trending": "Trending",
    "footer.category": "By Category",
    "footer.artists": "Artists",
    "footer.register": "Register as Artist",
    "footer.monetize": "Monetize Your Art",
    "footer.resources": "Resources",
    "footer.support": "Support",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.refund": "Refund Policy",
    "explore": "Explore Events",
    "search.eventType": "Event Type",
    "search.eventPlaceholder": "Music, Jatra, Cinema...",
    "search.location": "Location",
    "search.locationPlaceholder": "City or ZIP code",
    "search.date": "Date",
    "search.button": "Search",
    "category.discover": "Discover",
    "category.eventsNow": "events happening now",
    "category.viewAll": "View All",
    "card.featured": "Featured",
    "card.free": "Free",
    "card.attending": "attending",
    "card.online": "Online",
    "card.view": "View",
    "filters.title": "Filters",
    "filters.clearAll": "Clear All",
    "filters.category": "Category",
    "filters.location": "Location",
    "filters.locationPlaceholder": "City or ZIP",
    "filters.priceRange": "Price Range",
    "filters.min": "Min",
    "filters.max": "Max",
    "filters.eventType": "Event Type",
    "filters.allTypes": "All Types",
    "filters.corporate": "Corporate event",
    "filters.social": "Social events",
    "filters.entertainment": "Entertainment & public events",
    "filters.education": "Education e-learning & Youth events",
    "filters.charity": "Charity & community events",
    "filters.virtual": "Virtual event",
    "filters.casting": "Casting Audition",
    "grid.noEvents": "No events found. Try adjusting your filters.",
    "grid.loading": "Loading more events...",
    "newsletter.title": "Stay Updated",
    "newsletter.subtitle": "Get the latest events delivered to your inbox. Never miss out on amazing experiences.",
    "newsletter.placeholder": "Enter your email",
    "newsletter.subscribe": "Subscribe",
    "newsletter.subscribed": "Subscribed!",
    "inquiry.title": "Inquiry Form",
    "inquiry.subtitle": "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "inquiry.firstNamePlaceholder": "First Name",
    "inquiry.lastNamePlaceholder": "Last Name",
    "inquiry.phonePlaceholder": "Phone Number",
    "inquiry.emailPlaceholder": "Email Address",
    "inquiry.cityPlaceholder": "City",
    "inquiry.messagePlaceholder": "Your Message",
    "inquiry.submit": "Send Message",
    "inquiry.success": "Thank You!",
    "inquiry.successMessage": "Your inquiry has been submitted successfully. We'll get back to you soon.",
    "terms.title": "Terms of Service",
    "terms.subtitle": "Please read these terms carefully",
    "terms.updated": "Last updated: December 2024",
    "terms.section1": "1. Acceptance of Terms",
    "terms.section1.text": "By accessing and using MOOKALAA, you accept and agree to be bound by the terms and provision of this agreement.",
    "terms.section2": "2. Description of Service",
    "terms.section2.text": "MOOKALAA is a platform that connects users with arts and cultural events including Jatra, Cinema, Music, Dance, Festivals, Workshops, and Custom Orders from artists worldwide.",
    "terms.section3": "3. User Accounts",
    "terms.section3.text": "To access certain features, you must create an account. You are responsible for:",
    "terms.section4": "4. Booking and Payments",
    "terms.section4.text": "When you book an event through MOOKALAA:",
    "terms.section5": "5. User Conduct",
    "terms.section5.text": "You agree not to:",
    "terms.section6": "6. Event Organizers",
    "terms.section6.text": "Event organizers using MOOKALAA agree to:",
    "terms.section7": "7. Intellectual Property",
    "terms.section7.text": "The MOOKALAA platform, including its content, features, and functionality, is owned by MOOKALAA and is protected by copyright, trademark, and other intellectual property laws.",
    "terms.section8": "8. Disclaimers",
    "terms.section8.text": "MOOKALAA provides the platform 'as is' without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of any content or services.",
    "terms.section9": "9. Limitation of Liability",
    "terms.section9.text": "MOOKALAA shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.",
    "terms.section10": "10. Termination",
    "terms.section10.text": "We may terminate or suspend your account and access to the service at our sole discretion, without prior notice, for conduct that we believe violates these Terms.",
    "terms.section11": "11. Changes to Terms",
    "terms.section11.text": "We reserve the right to modify these terms at any time. We will notify users of any material changes via email or through the platform.",
    "terms.section12": "12. Contact Information",
    "terms.section12.text": "If you have any questions about these Terms of Service, please contact us at:",
    "terms.bullet3.1": "Maintaining the confidentiality of your account credentials",
    "terms.bullet3.2": "All activities that occur under your account",
    "terms.bullet3.3": "Providing accurate and complete information",
    "terms.bullet3.4": "Updating your information as necessary",
    "terms.bullet4.1": "You agree to pay all applicable fees",
    "terms.bullet4.2": "Payments are processed securely through third-party providers",
    "terms.bullet4.3": "Booking confirmations are subject to event organizer approval",
    "terms.bullet4.4": "Cancellation policies vary by event and organizer",
    "terms.bullet5.1": "Use the service for any unlawful purpose",
    "terms.bullet5.2": "Interfere with or disrupt the service",
    "terms.bullet5.3": "Upload harmful or malicious content",
    "terms.bullet5.4": "Violate any applicable laws or regulations",
    "terms.bullet5.5": "Infringe on intellectual property rights",
    "terms.bullet6.1": "Provide accurate event information",
    "terms.bullet6.2": "Honor confirmed bookings",
    "terms.bullet6.3": "Comply with applicable laws and regulations",
    "terms.bullet6.4": "Maintain appropriate insurance coverage",
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Your privacy is important to us",
    "privacy.updated": "Last updated: December 2024",
    "privacy.section1": "1. Information We Collect",
    "privacy.section1.text": "At MOOKALAA, we collect information you provide directly to us, such as when you create an account, book events, or contact us for support.",
    "privacy.section2": "2. How We Use Your Information",
    "privacy.section2.text": "We use the information we collect to:",
    "privacy.section3": "3. Information Sharing",
    "privacy.section3.text1": "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy.",
    "privacy.section3.text2": "We may share your information with:",
    "privacy.section4": "4. Data Security",
    "privacy.section4.text": "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    "privacy.section5": "5. Your Rights",
    "privacy.section5.text": "You have the right to:",
    "privacy.section6": "6. Cookies and Tracking",
    "privacy.section6.text": "We use cookies and similar technologies to enhance your experience, analyze usage, and provide personalized content.",
    "privacy.section7": "7. Contact Us",
    "privacy.section7.text": "If you have any questions about this Privacy Policy, please contact us at:",
    "privacy.bullet1.1": "Personal information (name, email, phone number)",
    "privacy.bullet1.2": "Payment information (processed securely through third-party providers)",
    "privacy.bullet1.3": "Event preferences and booking history",
    "privacy.bullet1.4": "Communication preferences",
    "privacy.bullet2.1": "Provide and improve our services",
    "privacy.bullet2.2": "Process bookings and payments",
    "privacy.bullet2.3": "Send you event recommendations and updates",
    "privacy.bullet2.4": "Provide customer support",
    "privacy.bullet2.5": "Comply with legal obligations",
    "privacy.bullet3.1": "Event organizers (only necessary booking details)",
    "privacy.bullet3.2": "Payment processors for transaction processing",
    "privacy.bullet3.3": "Service providers who assist in our operations",
    "privacy.bullet3.4": "Legal authorities when required by law",
    "privacy.bullet5.1": "Access your personal information",
    "privacy.bullet5.2": "Correct inaccurate information",
    "privacy.bullet5.3": "Delete your account and personal information",
    "privacy.bullet5.4": "Opt-out of marketing communications",
    "privacy.bullet5.5": "Data portability",
    "eventDetail.notFound": "Event Not Found",
    "eventDetail.backToEvents": "Back to Events",
    "eventDetail.date": "Date",
    "eventDetail.time": "Time",
    "eventDetail.location": "Location",
    "eventDetail.attending": "Attending",
    "eventDetail.addToCalendar": "Add to Calendar",
    "eventDetail.aboutOrganizer": "About the Organizer",
    "eventDetail.relatedEvents": "Related Events",
    "eventDetail.eventInfo": "Event Info",
    "eventDetail.entryFee": "Entry Fee",
    "eventDetail.eventType": "EVENT TYPE",
    "eventDetail.onlineEvent": "Online Event",
    "eventDetail.inPerson": "In-Person",
    "eventDetail.attendees": "ATTENDEES",
    "eventDetail.markInterested": "Mark as Interested",
    "eventDetail.shareEvent": "Share Event",
    "eventDetail.tags": "TAGS",
    "eventDetail.bookTicket": "Book Ticket",
    "trending.title": "Trending Cities",
    "trending.subtitle": "Explore events in popular destinations",
    "trending.events": "events",
    "eventsPage.title": "Discover Events",
    "eventsPage.found": "Found",
    "eventsPage.events": "events",
    "eventsPage.gridView": "Grid View",
    "eventsPage.mapView": "Map View",
    "eventsPage.sortPopular": "Most Popular",
    "eventsPage.sortDate": "Nearest Date",
    "eventsPage.sortRecent": "Recently Added",
    "categories.Jatra": "Jatra",
    "categories.Cinema": "Cinema",
    "categories.Ollywood": "Ollywood",
    "categories.Jollywood": "Jollywood",
    "categories.Music": "Music",
    "categories.Influencer": "Influencer",
    "categories.Comedian": "Comedian",
    "categories.Sports": "Sports",
    "categories.YouTuber's": "YouTuber's",
    "categories.Dancer": "Dancer",
    "categories.Authors": "Authors",
    "categories.Poet": "Poet",
    "categories.Indian idol contestants": "Indian Idol Contestants",
    "categories.Indian idol Artist": "Indian Idol Artist",
    "categories.Theatre Artists": "Theatre Artists",
    "categories.Instrumentalist": "Instrumentalist",
    "categories.Magician": "Magician",
    "categories.RJ": "RJ",
    "event.2.title": "Jatra Theatre Festival",
    "event.2.description": "Immerse yourself in the vibrant world of Jatra - traditional folk theatre. Experience compelling narratives performed by master artists.",
    "event.33.title": "Cricket Championship Finals",
    "event.33.description": "Watch the thrilling finals of the city cricket championship live.",
    "event.34.title": "Marathon Run 2025",
    "event.34.description": "Participate in the annual city marathon and promote fitness and health.",
    "event.8.title": "Global Arts Summit - New York",
    "event.8.description": "Connect with international artists, curators, and culture enthusiasts. Showcase your work to a global audience.",
    "event.15.title": "Odissi Dance Festival",
    "event.15.description": "Experience the divine grace of Odissi dance with master performers showcasing classical choreography and contemporary interpretations.",
    "event.48.title": "Indian Idol Concert",
    "event.48.description": "Watch Indian Idol contestants perform live in this spectacular musical concert.",
    "event.22.title": "Ollywood Music Awards 2025",
    "event.22.description": "Annual awards ceremony celebrating the best of Odia film music and artists.",
    "event.1.title": "Odissi Dance Festival 2025",
    "event.1.description": "Celebrate the grace and elegance of Odissi dance with performances from acclaimed dancers. Experience traditional choreography and contemporary interpretations.",
    "event.35.title": "Football Tournament",
    "event.35.description": "Inter-city football tournament featuring top local teams.",
    "event.12.title": "Sitar Recital by Maestro",
    "event.12.description": "An evening of classical Hindustani music featuring maestro sitar player performing raags from morning to night traditions.",
    "event.14.title": "Photography Exhibition - Faces of India",
    "event.14.description": "A powerful photography exhibition showcasing portraits and stories of ordinary people from across India. Interactive artist talks.",
    "event.7.title": "Indian Classical Music Masterclass",
    "event.7.description": "Learn Indian classical music from Grammy-nominated musician. Cover raag theory, instrument techniques, and composition.",
    "event.18.title": "Indian Classical Music Concert",
    "event.18.description": "An enchanting evening of Indian classical music featuring renowned musicians performing traditional ragas and compositions.",
    "event.31.title": "Comedy Festival 2025",
    "event.31.description": "Three days of non-stop laughter with India's best comedians.",
    "event.37.title": "YouTube Creator Summit",
    "event.37.description": "Learn monetization strategies and growth hacks from successful YouTubers.",
    "event.3.title": "Learn Kathak Dance Online",
    "event.3.description": "Master the fundamentals of Kathak dance in this comprehensive online workshop. Learn from Kathak maestro with personalized feedback.",
    "event.10.title": "Digital Art & Animation Expo",
    "event.10.description": "Showcase digital artworks, animations, and interactive installations from emerging digital artists. Networking with tech & art professionals.",
    "event.17.title": "Traditional Jatra Folk Theatre",
    "event.17.description": "Experience authentic Bengali folk theatre with traditional Jatra performances featuring mythological stories and social themes.",
    "organizer.Odissi Classical Arts": "Odissi Classical Arts",
    "organizer.Global Jatra Collective": "Global Jatra Collective",
    "organizer.MOOKALAA Artists Network": "MOOKALAA Artists Network",
    "organizer.Dance India Movement": "Dance India Movement",
    "booking.venue": "Venue",
    "booking.dateTime": "Date & Time",
    "booking.ticket": "Ticket",
    "booking.proceedToPay": "Proceed to Pay",
    "booking.selectVenue": "Select Venue",
    "booking.selectDate": "Select Date",
    "booking.selectTime": "Select Time",
    "booking.selectTickets": "Select Tickets",
    "booking.reviewProceed": "Review & Proceed to Pay",
    "booking.available": "Available",
    "booking.fastFilling": "Fast Filling",
    "booking.soldOut": "Sold out",
    "booking.proceed": "Proceed",
    "booking.general": "General",
    "booking.vip": "VIP",
    "booking.premium": "Premium",
    "booking.perTicket": "per ticket",
    "booking.mTicket": "M-Ticket",
    "booking.savePlanet": "Save the planet. Use your phone as a ticket.",
    "booking.mTicketInfo": "M-Ticket Information",
    "booking.mTicketPoint1": "1. Customer(s) can access their ticket(s) from the 'My Profile' section on the app/mobile-web.",
    "booking.mTicketPoint2": "2. It is mandatory to present the ticket(s) in my profile section via app/mobile-web at the venue.",
    "booking.mTicketPoint3": "3. No physical ticket(s) are required to enter the venue.",
    "booking.subTotal": "Sub-total",
    "booking.bookingFee": "Booking Fee",
    "booking.totalAmount": "Total Amount",
    "booking.selectState": "Select State",
    "booking.consent": "By proceeding, I express my consent to complete this transaction.",
    "booking.tickets": "Tickets",
    "payment.title": "Payment",
    "payment.selectMethod": "Select Payment Method",
    "payment.upi": "UPI",
    "payment.upiDesc": "Pay using UPI apps",
    "payment.creditDebit": "Credit/Debit Card",
    "payment.cardDesc": "Visa, Mastercard, Rupay",
    "payment.netBanking": "Net Banking",
    "payment.netBankingDesc": "All major banks supported",
    "payment.wallets": "Wallets",
    "payment.walletsDesc": "Paytm, PhonePe, Google Pay",
    "payment.bookingSummary": "Booking Summary",
    "payment.priceBreakdown": "Price Breakdown",
    "payment.importantInfo": "Important Information:",
    "payment.instantConfirm": "• Your booking will be confirmed instantly",
    "payment.emailTicket": "• M-Ticket will be sent to your registered email",
    "payment.idProof": "• Please carry a valid ID proof to the venue",
    "payment.venueGuidelines": "• Entry is subject to venue guidelines",
    "payment.pay": "Pay",
    "payment.date": "Date:",
    "payment.time": "Time:",
    "payment.venue": "Venue:",
    "payment.tickets": "Tickets:",
    "booking.selectOptions": "Please select from the following option(s)",
    "booking.dateLabel": "Sun",
    "booking.viewMaps": "View on maps",
    "location.Rabindra Mandap, Bhubaneswar, Odissi": "Rabindra Mandap, Bhubaneswar, Odissi",
    "location.Siddeshwari Auditorium, Kolkata, West Bengal": "Siddeshwari Auditorium, Kolkata, West Bengal",
    "location.PVR Cinemas, Bangalore, Karnataka": "PVR Cinemas, Bangalore, Karnataka",
    "location.Cultural Centre, Delhi, India": "Cultural Centre, Delhi, India",
    "location.Ravindra Sarovar, Mumbai, Maharashtra": "Ravindra Sarovar, Mumbai, Maharashtra",
    "location.Lincoln Center, New York, USA": "Lincoln Center, New York, USA",
    "location.Arts Academy, Chennai, Tamil Nadu": "Arts Academy, Chennai, Tamil Nadu",
    "location.Tech Hub, Hyderabad, Telangana": "Tech Hub, Hyderabad, Telangana",
  },
  hi: {
    "hero.title": "अद्भुत कला और सांस्कृतिक कार्यक्रम खोजें",
    "hero.subtitle": "कला के माध्यम से एकजुट - जात्रा, सिनेमा, संगीत, नृत्य और अधिक खोजें",
    "stats.eventsBooked": "बुक किए गए कार्यक्रम",
    "stats.artists": "पंजीकृत कलाकार",
    "stats.tickets": "बेची गई टिकटें",
    "stats.learners": "सक्रिय शिक्षार्थी",
    "stats.orders": "कस्टम ऑर्डर",
    "featured.title": "विशेष कार्यक्रम",
    "featured.subtitle": "चुनिंदा कला और सांस्कृतिक अनुभव",
    "footer.discover": "खोजें",
    "footer.browse": "कार्यक्रम ब्राउज़ करें",
    "footer.trending": "ट्रेंडिंग",
    "footer.category": "श्रेणी के अनुसार",
    "footer.artists": "कलाकार",
    "footer.register": "कलाकार के रूप में पंजीकरण करें",
    "footer.monetize": "अपनी कला से कमाएं",
    "footer.resources": "संसाधन",
    "footer.support": "सहायता",
    "footer.legal": "कानूनी",
    "footer.privacy": "गोपनीयता",
    "footer.terms": "नियम",
    "footer.refund": "रिफंड नीति",
    "explore": "कार्यक्रम देखें",
    "search.eventType": "कार्यक्रम प्रकार",
    "search.eventPlaceholder": "संगीत, जात्रा, सिनेमा...",
    "search.location": "स्थान",
    "search.locationPlaceholder": "शहर या पिन कोड",
    "search.date": "तारीख",
    "search.button": "खोजें",
    "category.discover": "खोजें",
    "category.eventsNow": "कार्यक्रम अभी हो रहे हैं",
    "category.viewAll": "सभी देखें",
    "card.featured": "विशेष",
    "card.free": "मुफ्त",
    "card.attending": "उपस्थित",
    "card.online": "ऑनलाइन",
    "card.view": "देखें",
    "filters.title": "फ़िल्टर",
    "filters.clearAll": "सभी हटाएं",
    "filters.category": "श्रेणी",
    "filters.location": "स्थान",
    "filters.locationPlaceholder": "शहर या पिन कोड",
    "filters.priceRange": "मूल्य सीमा",
    "filters.min": "न्यूनतम",
    "filters.max": "अधिकतम",
    "filters.eventType": "कार्यक्रम प्रकार",
    "filters.allTypes": "सभी प्रकार",
    "filters.corporate": "कॉर्पोरेट कार्यक्रम",
    "filters.social": "सामाजिक कार्यक्रम",
    "filters.entertainment": "मनोरंजन और सार्वजनिक कार्यक्रम",
    "filters.education": "शिक्षा ई-लर्निंग और युवा कार्यक्रम",
    "filters.charity": "दान और सामुदायिक कार्यक्रम",
    "filters.virtual": "वर्चुअल कार्यक्रम",
    "filters.casting": "कास्टिंग ऑडिशन",
    "grid.noEvents": "कोई कार्यक्रम नहीं मिला। अपने फ़िल्टर समायोजित करने का प्रयास करें।",
    "grid.loading": "अधिक कार्यक्रम लोड हो रहे हैं...",
    "newsletter.title": "अपडेट रहें",
    "newsletter.subtitle": "अपने इनबॉक्स में नवीनतम कार्यक्रम प्राप्त करें। अद्भुत अनुभवों को कभी न चूकें।",
    "newsletter.placeholder": "अपना ईमेल दर्ज करें",
    "newsletter.subscribe": "सब्सक्राइब करें",
    "newsletter.subscribed": "सब्सक्राइब हो गया!",
    "inquiry.title": "पूछताछ फॉर्म",
    "inquiry.subtitle": "कोई प्रश्न है? हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें और हम जल्द से जल्द जवाब देंगे।",
    "inquiry.firstNamePlaceholder": "पहला नाम",
    "inquiry.lastNamePlaceholder": "अंतिम नाम",
    "inquiry.phonePlaceholder": "फोन नंबर",
    "inquiry.emailPlaceholder": "ईमेल पता",
    "inquiry.cityPlaceholder": "शहर",
    "inquiry.messagePlaceholder": "आपका संदेश",
    "inquiry.submit": "संदेश भेजें",
    "inquiry.success": "धन्यवाद!",
    "inquiry.successMessage": "आपकी पूछताछ सफलतापूर्वक जमा कर दी गई है। हम जल्द ही आपसे संपर्क करेंगे।",
    "terms.title": "सेवा की शर्तें",
    "terms.subtitle": "कृपया इन शर्तों को ध्यान से पढ़ें",
    "terms.updated": "अंतिम अपडेट: दिसंबर 2024",
    "terms.section1": "1. शर्तों की स्वीकृति",
    "terms.section1.text": "MOOKALAA तक पहुंचकर और उपयोग करके, आप इस समझौते की शर्तों और प्रावधानों से बंधे रहने के लिए स्वीकार करते हैं और सहमत होते हैं।",
    "terms.section2": "2. सेवा का विवरण",
    "terms.section2.text": "MOOKALAA एक मंच है जो उपयोगकर्ताओं को जात्रा, सिनेमा, संगीत, नृत्य, त्योहार, कार्यशालाओं और दुनिया भर के कलाकारों से कस्टम ऑर्डर सहित कला और सांस्कृतिक कार्यक्रमों से जोड़ता है।",
    "terms.section3": "3. उपयोगकर्ता खाते",
    "terms.section3.text": "कुछ सुविधाओं तक पहुंचने के लिए, आपको एक खाता बनाना होगा। आप निम्नलिखित के लिए जिम्मेदार हैं:",
    "terms.section4": "4. बुकिंग और भुगतान",
    "terms.section4.text": "जब आप MOOKALAA के माध्यम से कोई कार्यक्रम बुक करते हैं:",
    "terms.section5": "5. उपयोगकर्ता आचरण",
    "terms.section5.text": "आप सहमत हैं कि आप निम्नलिखित नहीं करेंगे:",
    "terms.section6": "6. कार्यक्रम आयोजक",
    "terms.section6.text": "MOOKALAA का उपयोग करने वाले कार्यक्रम आयोजक सहमत हैं:",
    "terms.section7": "7. बौद्धिक संपदा",
    "terms.section7.text": "MOOKALAA प्लेटफॉर्म, इसकी सामग्री, सुविधाओं और कार्यक्षमता का स्वामित्व MOOKALAA के पास है और यह कॉपीराइट, ट्रेडमार्क और अन्य बौद्धिक संपदा कानूनों द्वारा संरक्षित है।",
    "terms.section8": "8. अस्वीकरण",
    "terms.section8.text": "MOOKALAA प्लेटफॉर्म को 'जैसा है' किसी भी प्रकार की वारंटी के बिना प्रदान करता है। हम किसी भी सामग्री या सेवाओं की सटीकता, पूर्णता या विश्वसनीयता की गारंटी नहीं देते हैं।",
    "terms.section9": "9. दायित्व की सीमा",
    "terms.section9.text": "MOOKALAA आपकी सेवा के उपयोग से उत्पन्न किसी भी अप्रत्यक्ष, आकस्मिक, विशेष, परिणामी या दंडात्मक नुकसान के लिए उत्तरदायी नहीं होगा।",
    "terms.section10": "10. समाप्ति",
    "terms.section10.text": "हम अपने विवेक पर, बिना पूर्व सूचना के, आपके खाते और सेवा तक पहुंच को समाप्त या निलंबित कर सकते हैं, उस आचरण के लिए जो हमारे विचार में इन शर्तों का उल्लंघन करता है।",
    "terms.section11": "11. शर्तों में परिवर्तन",
    "terms.section11.text": "हम किसी भी समय इन शर्तों को संशोधित करने का अधिकार सुरक्षित रखते हैं। हम ईमेल या प्लेटफॉर्म के माध्यम से उपयोगकर्ताओं को किसी भी महत्वपूर्ण परिवर्तन की सूचना देंगे।",
    "terms.section12": "12. संपर्क जानकारी",
    "terms.section12.text": "यदि इन सेवा की शर्तों के बारे में आपके कोई प्रश्न हैं, तो कृपया हमसे संपर्क करें:",
    "terms.bullet3.1": "अपने खाते की प्रमाण पत्रों की गोपनीयता बनाए रखना",
    "terms.bullet3.2": "आपके खाते के तहत होने वाली सभी गतिविधियां",
    "terms.bullet3.3": "सटीक और पूर्ण जानकारी प्रदान करना",
    "terms.bullet3.4": "आवश्यकतानुसार अपनी जानकारी अपडेट करना",
    "terms.bullet4.1": "आप सभी लागू शुल्क का भुगतान करने के लिए सहमत हैं",
    "terms.bullet4.2": "भुगतान तीसरे पक्ष प्रदाताओं के माध्यम से सुरक्षित रूप से संसाधित किए जाते हैं",
    "terms.bullet4.3": "बुकिंग पुष्टिकरण कार्यक्रम आयोजक की स्वीकृति के अधीन है",
    "terms.bullet4.4": "रद्द करने की नीतियां कार्यक्रम और आयोजक के अनुसार भिन्न होती हैं",
    "terms.bullet5.1": "किसी भी गैरकानूनी उद्देश्य के लिए सेवा का उपयोग करना",
    "terms.bullet5.2": "सेवा में हस्तक्षेप करना या बाधित करना",
    "terms.bullet5.3": "हानिकारक या दुर्भावनापूर्ण सामग्री अपलोड करना",
    "terms.bullet5.4": "किसी भी लागू कानून या विनियमों का उल्लंघन करना",
    "terms.bullet5.5": "बौद्धिक संपदा अधिकारों का उल्लंघन करना",
    "terms.bullet6.1": "सटीक कार्यक्रम जानकारी प्रदान करना",
    "terms.bullet6.2": "पुष्टिकृत बुकिंग का सम्मान करना",
    "terms.bullet6.3": "लागू कानूनों और विनियमों का पालन करना",
    "terms.bullet6.4": "उचित बीमा कवरेज बनाए रखना",
    "privacy.title": "गोपनीयता नीति",
    "privacy.subtitle": "आपकी गोपनीयता हमारे लिए महत्वपूर्ण है",
    "privacy.updated": "अंतिम अपडेट: दिसंबर 2024",
    "privacy.section1": "1. हम कौन सी जानकारी एकत्र करते हैं",
    "privacy.section1.text": "MOOKALAA में, हम वह जानकारी एकत्र करते हैं जो आप सीधे हमें प्रदान करते हैं, जैसे कि जब आप खाता बनाते हैं, कार्यक्रम बुक करते हैं, या सहायता के लिए हमसे संपर्क करते हैं।",
    "privacy.section2": "2. हम आपकी जानकारी का उपयोग कैसे करते हैं",
    "privacy.section2.text": "हम एकत्रित जानकारी का उपयोग निम्नलिखित के लिए करते हैं:",
    "privacy.section3": "3. जानकारी साझा करना",
    "privacy.section3.text1": "हम आपकी सहमति के बिना आपकी व्यक्तिगत जानकारी को तीसरे पक्ष को नहीं बेचते, व्यापार नहीं करते या स्थानांतरित नहीं करते हैं, सिवाय इस नीति में वर्णित के अनुसार।",
    "privacy.section3.text2": "हम आपकी जानकारी निम्नलिखित के साथ साझा कर सकते हैं:",
    "privacy.section4": "4. डेटा सुरक्षा",
    "privacy.section4.text": "हम आपकी व्यक्तिगत जानकारी को अनधिकृत पहुंच, परिवर्तन, प्रकटीकरण या विनाश से बचाने के लिए उचित सुरक्षा उपाय लागू करते हैं।",
    "privacy.section5": "5. आपके अधिकार",
    "privacy.section5.text": "आपको निम्नलिखित अधिकार हैं:",
    "privacy.section6": "6. कुकीज़ और ट्रैकिंग",
    "privacy.section6.text": "हम आपके अनुभव को बढ़ाने, उपयोग का विश्लेषण करने और वैयक्तिकृत सामग्री प्रदान करने के लिए कुकीज़ और समान तकनीकों का उपयोग करते हैं।",
    "privacy.section7": "7. हमसे संपर्क करें",
    "privacy.section7.text": "यदि इस गोपनीयता नीति के बारे में आपके कोई प्रश्न हैं, तो कृपया हमसे संपर्क करें:",
    "privacy.bullet1.1": "व्यक्तिगत जानकारी (नाम, ईमेल, फोन नंबर)",
    "privacy.bullet1.2": "भुगतान जानकारी (तीसरे पक्ष प्रदाताओं के माध्यम से सुरक्षित रूप से संसाधित)",
    "privacy.bullet1.3": "कार्यक्रम पसंद और बुकिंग इतिहास",
    "privacy.bullet1.4": "संचार पसंद",
    "privacy.bullet2.1": "हमारी सेवाओं को प्रदान और सुधारना",
    "privacy.bullet2.2": "बुकिंग और भुगतान संसाधित करना",
    "privacy.bullet2.3": "आपको कार्यक्रम सिफारिशें और अपडेट भेजना",
    "privacy.bullet2.4": "ग्राहक सहायता प्रदान करना",
    "privacy.bullet2.5": "कानूनी दायित्वों का पालन करना",
    "privacy.bullet3.1": "कार्यक्रम आयोजक (केवल आवश्यक बुकिंग विवरण)",
    "privacy.bullet3.2": "लेनदेन प्रसंस्करण के लिए भुगतान प्रोसेसर",
    "privacy.bullet3.3": "सेवा प्रदाता जो हमारे संचालन में सहायता करते हैं",
    "privacy.bullet3.4": "कानून द्वारा आवश्यक होने पर कानूनी अधिकारी",
    "privacy.bullet5.1": "अपनी व्यक्तिगत जानकारी तक पहुंचें",
    "privacy.bullet5.2": "गलत जानकारी को सही करें",
    "privacy.bullet5.3": "अपना खाता और व्यक्तिगत जानकारी हटाएं",
    "privacy.bullet5.4": "मार्केटिंग संचार से ऑप्ट-आउट करें",
    "privacy.bullet5.5": "डेटा पोर्टेबिलिटी",
    "eventDetail.notFound": "कार्यक्रम नहीं मिला",
    "eventDetail.backToEvents": "कार्यक्रमों पर वापस जाएं",
    "eventDetail.date": "तारीख",
    "eventDetail.time": "समय",
    "eventDetail.location": "स्थान",
    "eventDetail.attending": "उपस्थित",
    "eventDetail.addToCalendar": "कैलेंडर में जोड़ें",
    "eventDetail.aboutOrganizer": "आयोजक के बारे में",
    "eventDetail.relatedEvents": "संबंधित कार्यक्रम",
    "eventDetail.eventInfo": "कार्यक्रम जानकारी",
    "eventDetail.entryFee": "प्रवेश शुल्क",
    "eventDetail.eventType": "कार्यक्रम प्रकार",
    "eventDetail.onlineEvent": "ऑनलाइन कार्यक्रम",
    "eventDetail.inPerson": "व्यक्तिगत रूप से",
    "eventDetail.attendees": "उपस्थित लोग",
    "eventDetail.markInterested": "रुचि के रूप में चिह्नित करें",
    "eventDetail.shareEvent": "कार्यक्रम साझा करें",
    "eventDetail.tags": "टैग",
    "eventDetail.bookTicket": "टिकट बुक करें",
    "trending.title": "ट्रेंडिंग शहर",
    "trending.subtitle": "लोकप्रिय गंतव्यों में कार्यक्रमों का अन्वेषण करें",
    "trending.events": "कार्यक्रम",
    "eventsPage.title": "कार्यक्रम खोजें",
    "eventsPage.found": "मिले",
    "eventsPage.events": "कार्यक्रम",
    "eventsPage.gridView": "ग्रिड व्यू",
    "eventsPage.mapView": "मैप व्यू",
    "eventsPage.sortPopular": "सबसे लोकप्रिय",
    "eventsPage.sortDate": "निकटतम तारीख",
    "eventsPage.sortRecent": "हाल ही में जोड़े गए",
    "categories.Jatra": "जात्रा",
    "categories.Cinema": "सिनेमा",
    "categories.Ollywood": "ओलीवुड",
    "categories.Jollywood": "जॉलीवुड",
    "categories.Music": "संगीत",
    "categories.Influencer": "प्रभावक",
    "categories.Comedian": "कॉमेडियन",
    "categories.Sports": "खेल",
    "categories.YouTuber's": "यूट्यूबर",
    "categories.Dancer": "नर्तक",
    "categories.Authors": "लेखक",
    "categories.Poet": "कवि",
    "categories.Indian idol contestants": "इंडियन आइडल प्रतियोगी",
    "categories.Indian idol Artist": "इंडियन आइडल कलाकार",
    "categories.Theatre Artists": "रंगमंच कलाकार",
    "categories.Instrumentalist": "वाद्ययंत्र वादक",
    "categories.Magician": "जादूगर",
    "categories.RJ": "आरजे",
    "event.2.title": "जात्रा थिएटर फेस्टिवल",
    "event.2.description": "जात्रा की जीवंत दुनिया में डूब जाएं - पारंपरिक लोक रंगमंच। मास्टर कलाकारों द्वारा प्रस्तुत सम्मोहक कथाओं का अनुभव करें।",
    "event.33.title": "क्रिकेट चैंपियनशिप फाइनल",
    "event.33.description": "शहर की क्रिकेट चैंपियनशिप के रोमांचक फाइनल को लाइव देखें।",
    "event.34.title": "मैराथन रन 2025",
    "event.34.description": "वार्षिक शहर मैराथन में भाग लें और फिटनेस और स्वास्थ्य को बढ़ावा दें।",
    "event.8.title": "ग्लोबल आर्ट्स समिट - न्यूयॉर्क",
    "event.8.description": "अंतर्राष्ट्रीय कलाकारों, क्यूरेटरों और संस्कृति प्रेमियों से जुड़ें। अपने काम को वैश्विक दर्शकों के सामने प्रदर्शित करें।",
    "event.15.title": "ओडिसी नृत्य महोत्सव",
    "event.15.description": "शास्त्रीय नृत्यकला और समकालीन व्याख्याओं को प्रदर्शित करने वाले मास्टर कलाकारों के साथ ओडिसी नृत्य की दिव्य कृपा का अनुभव करें।",
    "event.48.title": "इंडियन आइडल कॉन्सर्ट",
    "event.48.description": "इस शानदार संगीत कॉन्सर्ट में इंडियन आइडल प्रतियोगियों को लाइव प्रदर्शन करते देखें।",
    "event.22.title": "ओलीवुड संगीत पुरस्कार 2025",
    "event.22.description": "ओड़िया फिल्म संगीत और कलाकारों के सर्वश्रेष्ठ का जश्न मनाने वाला वार्षिक पुरस्कार समारोह।",
    "event.1.title": "ओडिसी नृत्य महोत्सव 2025",
    "event.1.description": "प्रशंसित नर्तकों के प्रदर्शन के साथ ओडिसी नृत्य की कृपा और सुंदरता का जश्न मनाएं। पारंपरिक नृत्यकला और समकालीन व्याख्याओं का अनुभव करें।",
    "event.35.title": "फुटबॉल टूर्नामेंट",
    "event.35.description": "शीर्ष स्थानीय टीमों की विशेषता वाला अंतर-शहर फुटबॉल टूर्नामेंट।",
    "event.12.title": "मास्टरो द्वारा सितार वादन",
    "event.12.description": "शास्त्रीय हिंदुस्तानी संगीत की एक शाम जिसमें मास्टरो सितार वादक सुबह से रात की परंपराओं से राग प्रस्तुत करते हैं।",
    "event.14.title": "फोटोग्राफी प्रदर्शनी - भारत के चेहरे",
    "event.14.description": "पूरे भारत से आम लोगों के चित्र और कहानियों को प्रदर्शित करने वाली एक शक्तिशाली फोटोग्राफी प्रदर्शनी। इंटरैक्टिव कलाकार वार्ता।",
    "event.7.title": "भारतीय शास्त्रीय संगीत मास्टरक्लास",
    "event.7.description": "ग्रैमी-नामांकित संगीतकार से भारतीय शास्त्रीय संगीत सीखें। राग सिद्धांत, वाद्ययंत्र तकनीक और रचना को कवर करें।",
    "event.18.title": "भारतीय शास्त्रीय संगीत कॉन्सर्ट",
    "event.18.description": "प्रसिद्ध संगीतकारों द्वारा पारंपरिक राग और रचनाओं का प्रदर्शन करते हुए भारतीय शास्त्रीय संगीत की एक मनमोहक शाम।",
    "event.31.title": "कॉमेडी फेस्टिवल 2025",
    "event.31.description": "भारत के सर्वश्रेष्ठ कॉमेडियनों के साथ तीन दिन की नॉन-स्टॉप हंसी।",
    "event.37.title": "यूट्यूब क्रिएटर समिट",
    "event.37.description": "सफल यूट्यूबर्स से मुद्रीकरण रणनीतियां और विकास हैक्स सीखें।",
    "event.3.title": "कथक नृत्य ऑनलाइन सीखें",
    "event.3.description": "इस व्यापक ऑनलाइन कार्यशाला में कथक नृत्य की मूल बातों में माहिर बनें। व्यक्तिगत फीडबैक के साथ कथक मास्टरो से सीखें।",
    "event.10.title": "डिजिटल आर्ट एंड एनिमेशन एक्सपो",
    "event.10.description": "उभरते डिजिटल कलाकारों से डिजिटल कलाकृतियों, एनिमेशन और इंटरैक्टिव स्थापनाओं का प्रदर्शन। तकनीक और कला पेशेवरों के साथ नेटवर्किंग।",
    "event.17.title": "पारंपरिक जात्रा लोक रंगमंच",
    "event.17.description": "पौराणिक कथाओं और सामाजिक विषयों की विशेषता वाले पारंपरिक जात्रा प्रदर्शन के साथ प्रामाणिक बंगाली लोक रंगमंच का अनुभव करें।",
    "event.27.title": "सोशल मीडिया इन्फ्लुएंसर समिट",
    "event.27.description": "शीर्ष प्रभावकों से जुड़ें और अपनी सोशल मीडिया उपस्थिति बढ़ाने की रणनीतियां सीखें।",
    "event.44.title": "साहित्यिक महोत्सव 2025",
    "event.44.description": "पैनल चर्चा, पुस्तक पठन और लेखक बातचीत के साथ साहित्य का जश्न मनाएं।",
    "event.4.title": "इंडी सिनेमा शोकेस 2025",
    "event.4.description": "भारत और दुनिया भर के उभरते फिल्म निर्माताओं की स्वतंत्र फिल्मों की खोज करें। निर्देशकों के साथ प्रश्नोत्तर सत्र।",
    "event.36.title": "यूट्यूबर मीटअप 2025",
    "event.36.description": "लोकप्रिय यूट्यूबर्स से मिलें और सामग्री निर्माण और वीडियो उत्पादन के बारे में जानें।",
    "event.56.title": "फ्यूजन म्यूजिक नाइट",
    "event.56.description": "प्रतिभाशाली वाद्ययंत्र वादकों द्वारा पारंपरिक और आधुनिक संगीत के मिश्रण का अनुभव करें।",
    "event.59.title": "अंतर्राष्ट्रीय जादू महोत्सव",
    "event.59.description": "विश्व स्तरीय जादूगरों को अविश्वसनीय भ्रम और जादू के करतब दिखाते हुए देखें।",
    "event.16.title": "लाइव संगीत के साथ कथक नृत्य प्रदर्शन",
    "event.16.description": "लाइव शास्त्रीय संगीत के साथ कथक नृत्य की सुंदरता का अनुभव करें। मास्टर नर्तक तबला और सितार संगत के साथ पारंपरिक नृत्यकला प्रस्तुत करते हैं।",
    "event.28.title": "इन्फ्लुएंसर मीट एंड ग्रीट",
    "event.28.description": "अपने पसंदीदा सोशल मीडिया इन्फ्लुएंसर्स से व्यक्तिगत रूप से मिलें और विशेष सामग्री प्राप्त करें।",
    "event.52.title": "स्ट्रीट थिएटर फेस्टिवल",
    "event.52.description": "सामाजिक मुद्दों को संबोधित करने वाले आकर्षक स्ट्रीट थिएटर प्रदर्शन देखें।",
    "event.49.title": "इंडियन आइडल स्टार्स के साथ मीट एंड ग्रीट",
    "event.49.description": "अपने पसंदीदा इंडियन आइडल प्रतियोगियों के साथ विशेष मीट एंड ग्रीट सत्र।",
    "event.40.title": "हिप हॉप डांस बैटल",
    "event.40.description": "इस उच्च ऊर्जा नृत्य प्रतियोगिता में सर्वश्रेष्ठ हिप हॉप नर्तकों को प्रतिस्पर्धा करते देखें।",
    "event.54.title": "शास्त्रीय वाद्य संगीत कॉन्सर्ट",
    "event.54.description": "शास्त्रीय संगीत बजाने वाले मास्टर वाद्ययंत्र वादकों के मंत्रमुग्ध कर देने वाले प्रदर्शन का आनंद लें।",
    "event.11.title": "पारंपरिक कठपुतली रंगमंच शो - कठपुतली",
    "event.11.description": "पारंपरिक भारतीय लोककथाओं और पौराणिक कथाओं को दर्शाने वाले लाइव प्रदर्शन के साथ कठपुतली रंगमंच की प्राचीन कला का अनुभव करें।",
    "event.19.title": "डॉक्यूमेंट्री फिल्म फेस्टिवल",
    "event.19.description": "दुनिया भर से पुरस्कार विजेता डॉक्यूमेंट्री का एक क्यूरेटेड चयन, जिसमें संस्कृति, समाज और मानवीय अनुभवों की कहानियां हैं।",
    "event.20.title": "अंतर्राष्ट्रीय लघु फिल्म शोकेस",
    "event.20.description": "अंतर्राष्ट्रीय फिल्म निर्माताओं की पुरस्कार विजेता लघु फिल्मों का संग्रह, जो विविध कहानी कहने और नवीन छायांकन को प्रदर्शित करता है।",
    "event.25.title": "जॉलीवुड स्टार नाइट",
    "event.25.description": "इस विशेष फैन मीट और मनोरंजन रात में अपने पसंदीदा जॉलीवुड सितारों से मिलें।",
    "event.57.title": "जादू शो एक्सट्रावैगेंजा",
    "event.57.description": "पेशेवर जादूगरों द्वारा मन को चकित कर देने वाले जादू के करतब और भ्रम से हैरान हो जाएं।",
    "event.39.title": "समकालीन नृत्य प्रदर्शन",
    "event.39.description": "पेशेवर नर्तकों द्वारा शानदार समकालीन नृत्य प्रदर्शन का अनुभव करें।",
    "event.62.title": "लाइव रेडियो शो रिकॉर्डिंग",
    "event.62.description": "लोकप्रिय आरजे और सेलिब्रिटी मेहमानों के साथ लाइव रेडियो शो रिकॉर्डिंग का हिस्सा बनें।",
    "event.9.title": "शुरुआती लोगों के लिए भरतनाट्यम नृत्य कार्यशाला",
    "event.9.description": "अनुभवी प्रशिक्षकों से शास्त्रीय दक्षिण भारतीय नृत्य रूप भरतनाट्यम सीखें। बिना किसी पूर्व अनुभव वाले शुरुआती लोगों के लिए एकदम सही।",
    "event.21.title": "ओलीवुड फिल्म प्रीमियर नाइट",
    "event.21.description": "स्टार कास्ट मीट एंड ग्रीट के साथ नवीनतम ओड़िया ब्लॉकबस्टर फिल्म का विशेष प्रीमियर।",
    "event.30.title": "स्टैंड-अप कॉमेडी नाइट",
    "event.30.description": "शीर्ष कॉमेडियनों के साथ उनके सर्वश्रेष्ठ स्टैंड-अप रूटीन का प्रदर्शन करते हुए जोर से हंसें।",
    "event.51.title": "थिएटर प्ले - आधुनिक नाटक",
    "event.51.description": "इस समकालीन रंगमंच प्रस्तुति के माध्यम से शक्तिशाली कहानी कहने का अनुभव करें।",
    "event.24.title": "जॉलीवुड फिल्म फेस्टिवल",
    "event.24.description": "पुरस्कार विजेता जॉलीवुड फिल्मों की स्क्रीनिंग के साथ झारखंड सिनेमा का जश्न मनाएं।",
    "event.42.title": "पुस्तक लॉन्च और लेखक मुलाकात",
    "event.42.description": "इस विशेष पुस्तक लॉन्च कार्यक्रम में बेस्टसेलिंग लेखकों से मिलें और अपनी पुस्तकों पर हस्ताक्षर प्राप्त करें।",
    "event.13.title": "स्ट्रीट आर्ट एंड ग्रैफिटी कार्यशाला",
    "event.13.description": "पेशेवर स्ट्रीट आर्टिस्टों से शहरी कला और ग्रैफिटी तकनीक सीखें। उचित मार्गदर्शन और सुरक्षा के साथ अपना खुद का भित्तिचित्र बनाएं।",
    "event.29.title": "कंटेंट क्रिएटर कार्यशाला",
    "event.29.description": "सफल इन्फ्लुएंसर्स और क्रिएटर्स से कंटेंट क्रिएशन टिप्स और ट्रिक्स सीखें।",
    "event.60.title": "आरजे मीट एंड ग्रीट",
    "event.60.description": "अपने पसंदीदा रेडियो जॉकी से मिलें और रेडियो ब्रॉडकास्टिंग की दुनिया के बारे में जानें।",
    "event.38.title": "यूट्यूबर्स द्वारा वीडियो एडिटिंग कार्यशाला",
    "event.38.description": "पेशेवर यूट्यूबर्स से वीडियो एडिटिंग तकनीकों में माहिर बनें।",
    "event.58.title": "बच्चों के लिए जादू कार्यशाला",
    "event.58.description": "बच्चों के लिए डिज़ाइन की गई इस मजेदार कार्यशाला में सरल जादू के करतब सीखें।",
    "event.45.title": "कविता स्लैम प्रतियोगिता",
    "event.45.description": "लाइव प्रदर्शन के साथ इस रोमांचक कविता स्लैम में कवियों को प्रतिस्पर्धा करते देखें।",
    "event.5.title": "बॉलीवुड कलाकारों से कस्टम व्यक्तिगत गीत",
    "event.5.description": "पेशेवर बॉलीवुड गायकों से एक व्यक्तिगत गीत, जन्मदिन की शुभकामना, या विशेष संदेश का आदेश दें। जश्न के लिए एकदम सही!",
    "event.43.title": "लेखक कार्यशाला",
    "event.43.description": "पुरस्कार विजेता लेखकों से रचनात्मक लेखन तकनीक सीखें।",
    "event.50.title": "इंडियन आइडल गायन कार्यशाला",
    "event.50.description": "इस इंटरैक्टिव कार्यशाला में इंडियन आइडल प्रतियोगियों से गायन तकनीक सीखें।",
    "event.32.title": "ओपन माइक कॉमेडी नाइट",
    "event.32.description": "स्टैंड-अप कॉमेडी आजमाएं या उभरते कॉमेडियनों को प्रदर्शन करते देखें।",
    "event.46.title": "ओपन माइक कविता रात",
    "event.46.description": "इस ओपन माइक कविता सत्र में अपनी कविता साझा करें या सुंदर पंक्तियां सुनें।",
    "event.61.title": "रेडियो जॉकी कार्यशाला",
    "event.61.description": "पेशेवर आरजे से आवाज मॉड्यूलेशन, एंकरिंग और ब्रॉडकास्टिंग कौशल सीखें।",
    "event.53.title": "रंगमंच कलाकारों द्वारा अभिनय कार्यशाला",
    "event.53.description": "इस हाथों-हाथ कार्यशाला में अनुभवी रंगमंच कलाकारों से अभिनय कौशल सीखें।",
    "event.41.title": "शुरुआती लोगों के लिए नृत्य कार्यशाला",
    "event.41.description": "इस शुरुआती-अनुकूल कार्यशाला में पेशेवर नर्तकों से विभिन्न नृत्य शैलियां सीखें।",
    "event.55.title": "पेशेवर संगीतकारों द्वारा गिटार कार्यशाला",
    "event.55.description": "पेशेवर वाद्ययंत्र वादकों से गिटार तकनीक सीखें।",
    "event.23.title": "ओलीवुड अभिनेता कार्यशाला",
    "event.23.description": "इस गहन कार्यशाला में प्रसिद्ध ओलीवुड अभिनेताओं से अभिनय तकनीक सीखें।",
    "event.26.title": "जॉलीवुड फिल्ममेकिंग कार्यशाला",
    "event.26.description": "अनुभवी जॉलीवुड निर्देशकों और सिनेमैटोग्राफरों से फिल्म निर्माण की कला सीखें।",
    "event.47.title": "प्रसिद्ध कवियों के साथ कविता कार्यशाला",
    "event.47.description": "प्रसिद्ध कवियों से कविता लेखन की कला सीखें।",
    "event.6.title": "होली महोत्सव - संगीत और नृत्य उत्सव",
    "event.6.description": "लाइव संगीत प्रदर्शन, पारंपरिक नृत्यों और सांस्कृतिक उत्सवों के साथ रंगों के त्योहार का जश्न मनाएं।",
    "organizer.Odissi Classical Arts": "ओडिसी शास्त्रीय कला",
    "organizer.Global Jatra Collective": "ग्लोबल जात्रा समूह",
    "organizer.MOOKALAA Artists Network": "MOOKALAA कलाकार नेटवर्क",
    "organizer.Dance India Movement": "डांस इंडिया मूवमेंट",
    "booking.venue": "स्थान",
    "booking.dateTime": "दिनांक और समय",
    "booking.ticket": "टिकट",
    "booking.proceedToPay": "भुगतान करें",
    "booking.selectVenue": "स्थान चुनें",
    "booking.selectDate": "दिनांक चुनें",
    "booking.selectTime": "समय चुनें",
    "booking.selectTickets": "टिकट चुनें",
    "booking.reviewProceed": "समीक्षा करें और भुगतान के लिए आगे बढ़ें",
    "booking.available": "उपलब्ध",
    "booking.fastFilling": "तेजी से भर रहा है",
    "booking.soldOut": "बिक गया",
    "booking.proceed": "आगे बढ़ें",
    "booking.general": "सामान्य",
    "booking.vip": "वीआईपी",
    "booking.premium": "प्रीमियम",
    "booking.perTicket": "प्रति टिकट",
    "booking.mTicket": "एम-टिकट",
    "booking.savePlanet": "पृथ्वी को बचाएं। अपने फोन को टिकट के रूप में उपयोग करें।",
    "booking.mTicketInfo": "एम-टिकट जानकारी",
    "booking.mTicketPoint1": "1. ग्राहक अपने टिकट ऐप/मोबाइल-वेब पर 'मेरी प्रोफ़ाइल' सेक्शन से एक्सेस कर सकते हैं।",
    "booking.mTicketPoint2": "2. स्थल पर ऐप/मोबाइल-वेब के माध्यम से मेरी प्रोफ़ाइल सेक्शन में टिकट प्रस्तुत करना अनिवार्य है।",
    "booking.mTicketPoint3": "3. स्थल में प्रवेश के लिए कोई भौतिक टिकट की आवश्यकता नहीं है।",
    "booking.subTotal": "उप-योग",
    "booking.bookingFee": "बुकिंग शुल्क",
    "booking.totalAmount": "कुल राशि",
    "booking.selectState": "राज्य चुनें",
    "booking.consent": "आगे बढ़कर, मैं इस लेनदेन को पूरा करने के लिए अपनी सहमति व्यक्त करता हूं।",
    "booking.tickets": "टिकट",
    "payment.title": "भुगतान",
    "payment.selectMethod": "भुगतान विधि चुनें",
    "payment.upi": "यूपीआई",
    "payment.upiDesc": "यूपीआई ऐप्स का उपयोग करके भुगतान करें",
    "payment.creditDebit": "क्रेडिट/डेबिट कार्ड",
    "payment.cardDesc": "वीज़ा, मास्टरकार्ड, रुपे",
    "payment.netBanking": "नेट बैंकिंग",
    "payment.netBankingDesc": "सभी प्रमुख बैंक समर्थित",
    "payment.wallets": "वॉलेट",
    "payment.walletsDesc": "पेटीएम, फोनपे, गूगल पे",
    "payment.bookingSummary": "बुकिंग सारांश",
    "payment.priceBreakdown": "मूल्य विवरण",
    "payment.importantInfo": "महत्वपूर्ण जानकारी:",
    "payment.instantConfirm": "• आपकी बुकिंग तुरंत पुष्ट हो जाएगी",
    "payment.emailTicket": "• एम-टिकट आपके पंजीकृत ईमेल पर भेजा जाएगा",
    "payment.idProof": "• कृपया स्थल पर वैध आईडी प्रूफ लेकर आएं",
    "payment.venueGuidelines": "• प्रवेश स्थल दिशानिर्देशों के अधीन है",
    "payment.pay": "भुगतान करें",
    "payment.date": "दिनांक:",
    "payment.time": "समय:",
    "payment.venue": "स्थल:",
    "payment.tickets": "टिकट:",
    "booking.selectOptions": "कृपया निम्नलिखित विकल्प(ों) में से चुनें",
    "booking.dateLabel": "रविवार",
    "booking.viewMaps": "मैप पर देखें",
    "location.Rabindra Mandap, Bhubaneswar, Odissi": "रबीन्द्र मंडप, भुवनेश्वर, ओडिसी",
    "location.Siddeshwari Auditorium, Kolkata, West Bengal": "सिद्धेश्वरी ऑडिटोरियम, कोलकाता, पश्चिम बंगाल",
    "location.PVR Cinemas, Bangalore, Karnataka": "पीवीआर सिनेमा, बैंगलोर, कर्नाटक",
    "location.Cultural Centre, Delhi, India": "सांस्कृतिक केंद्र, दिल्ली, भारत",
    "location.Ravindra Sarovar, Mumbai, Maharashtra": "रवीन्द्र सरोवर, मुंबई, महाराष्ट्र",
    "location.Lincoln Center, New York, USA": "लिंकन सेंटर, न्यूयॉर्क, यूएसए",
    "location.Arts Academy, Chennai, Tamil Nadu": "आर्ट्स एकेडमी, चेन्नई, तमिलनाडु",
    "location.Tech Hub, Hyderabad, Telangana": "टेक हब, हैदराबाद, तेलंगाना",
    "event.63.title": "इंडियन आइडल कलाकार प्रदर्शन",
    "location.Bhubaneswar": "भुवनेश्वर",
    "location.Kolkata": "कोलकाता",
    "location.Virtual": "वर्चुअल",
    "location.Bangalore": "बैंगलोर",
    "location.Delhi": "दिल्ली",
    "location.Mumbai": "मुंबई",
    "location.New York": "न्यूयॉर्क",
    "location.Chennai": "चेन्नई",
    "location.Hyderabad": "हैदराबाद",
    "location.Jaipur": "जयपुर",
    "location.Pune": "पुणे",
    "location.Ahmedabad": "अहमदाबाद",
    "location.Odisha": "ओडिशा",
    "location.Cuttack": "कटक",
    "location.Ranchi": "रांची",
    "booking.proceed": "आगे बढ़ें",
  },
  bn: {
    "hero.title": "অসাধারণ শিল্প ও সাংস্কৃতিক অনুষ্ঠান আবিষ্কার করুন",
    "hero.subtitle": "শিল্পের মাধ্যমে একত্রিত হন - যাত্রা, সিনেমা, সঙ্গীত, নৃত্য এবং আরও অনেক কিছু খুঁজুন",
    "stats.eventsBooked": "বুক করা অনুষ্ঠান",
    "stats.artists": "নিবন্ধিত শিল্পী",
    "stats.tickets": "বিক্রিত টিকিট",
    "stats.learners": "সক্রিয় শিক্ষার্থী",
    "stats.orders": "কাস্টম অর্ডার",
    "featured.title": "বিশেষ অনুষ্ঠান",
    "featured.subtitle": "নির্বাচিত শিল্প ও সাংস্কৃতিক অভিজ্ঞতা",
    "footer.discover": "আবিষ্কার করুন",
    "footer.browse": "অনুষ্ঠান ব্রাউজ করুন",
    "footer.trending": "ট্রেন্ডিং",
    "footer.category": "বিভাগ অনুযায়ী",
    "footer.artists": "শিল্পী",
    "footer.register": "শিল্পী হিসেবে নিবন্ধন করুন",
    "footer.monetize": "আপনার শিল্প থেকে আয় করুন",
    "footer.resources": "সম্পদ",
    "footer.support": "সহায়তা",
    "footer.legal": "আইনি",
    "footer.privacy": "গোপনীয়তা",
    "footer.terms": "নিয়ম",
    "footer.refund": "রিফান্ড নীতি",
    "explore": "অনুষ্ঠান দেখুন",
    "search.eventType": "অনুষ্ঠানের ধরন",
    "search.eventPlaceholder": "সঙ্গীত, যাত্রা, সিনেমা...",
    "search.location": "অবস্থান",
    "search.locationPlaceholder": "শহর বা পিন কোড",
    "search.date": "তারিখ",
    "search.button": "খুঁজুন",
    "category.discover": "আবিষ্কার করুন",
    "category.eventsNow": "এখন চলমান অনুষ্ঠান",
    "category.viewAll": "সব দেখুন",
    "card.featured": "বিশেষ",
    "card.free": "বিনামূল্যে",
    "card.attending": "উপস্থিত",
    "card.online": "অনলাইন",
    "card.view": "দেখুন",
    "filters.title": "ফিল্টার",
    "filters.clearAll": "সব মুছুন",
    "filters.category": "বিভাগ",
    "filters.location": "অবস্থান",
    "filters.locationPlaceholder": "শহর বা পিন কোড",
    "filters.priceRange": "মূল্য পরিসীমা",
    "filters.min": "সর্বনিম্ন",
    "filters.max": "সর্বোচ্চ",
    "filters.eventType": "অনুষ্ঠানের ধরন",
    "filters.allTypes": "সব ধরন",
    "filters.corporate": "কর্পোরেট অনুষ্ঠান",
    "filters.social": "সামাজিক অনুষ্ঠান",
    "filters.entertainment": "বিনোদন ও পাবলিক অনুষ্ঠান",
    "filters.education": "শিক্ষা ই-লার্নিং ও যুব অনুষ্ঠান",
    "filters.charity": "দাতব্য ও কমিউনিটি অনুষ্ঠান",
    "filters.virtual": "ভার্চুয়াল অনুষ্ঠান",
    "filters.casting": "কাস্টিং অডিশন",
    "grid.noEvents": "কোন অনুষ্ঠান পাওয়া যায়নি। আপনার ফিল্টার সমন্বয় করার চেষ্টা করুন।",
    "grid.loading": "আরো অনুষ্ঠান লোড হচ্ছে...",
    "newsletter.title": "আপডেট থাকুন",
    "newsletter.subtitle": "আপনার ইনবক্সে সর্বশেষ অনুষ্ঠান পান। অসাধারণ অভিজ্ঞতা মিস করবেন না।",
    "newsletter.placeholder": "আপনার ইমেইল দিন",
    "newsletter.subscribe": "সাবস্ক্রাইব করুন",
    "newsletter.subscribed": "সাবস্ক্রাইব হয়েছে!",
    "inquiry.title": "অনুসন্ধান ফর্ম",
    "inquiry.subtitle": "কোন প্রশ্ন আছে? আমরা আপনার কাছ থেকে শুনতে চাই। আমাদের একটি বার্তা পাঠান এবং আমরা যত তাড়াতাড়ি সম্ভব উত্তর দেব।",
    "inquiry.firstNamePlaceholder": "প্রথম নাম",
    "inquiry.lastNamePlaceholder": "শেষ নাম",
    "inquiry.phonePlaceholder": "ফোন নম্বর",
    "inquiry.emailPlaceholder": "ইমেইল ঠিকানা",
    "inquiry.cityPlaceholder": "শহর",
    "inquiry.messagePlaceholder": "আপনার বার্তা",
    "inquiry.submit": "বার্তা পাঠান",
    "inquiry.success": "ধন্যবাদ!",
    "inquiry.successMessage": "আপনার অনুসন্ধান সফলভাবে জমা দেওয়া হয়েছে। আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।",
    "categories.Jatra": "যাত্রা",
    "categories.Cinema": "সিনেমা",
    "categories.Ollywood": "ওলিউড",
    "categories.Jollywood": "জলিউড",
    "categories.Music": "সঙ্গীত",
    "categories.Influencer": "প্রভাবশালী",
    "categories.Social Media": "সোশ্যাল মিডিয়া",
    "categories.Summit": "সামিট",
    "categories.Comedian": "কৌতুকাভিনেতা",
    "categories.Sports": "খেলাধুলা",
    "categories.YouTuber's": "ইউটিউবার",
    "categories.Dancer": "নর্তক",
    "categories.Authors": "লেখক",
    "categories.Poet": "কবি",
    "categories.Indian idol contestants": "ইন্ডিয়ান আইডল প্রতিযোগী",
    "categories.Indian idol Artist": "ইন্ডিয়ান আইডল শিল্পী",
    "categories.Theatre Artists": "থিয়েটার শিল্পী",
    "categories.Instrumentalist": "বাদ্যযন্ত্রী",
    "categories.Magician": "জাদুকর",
    "categories.RJ": "আরজে",
    "categories.YouTube": "ইউটিউব",
    "categories.Content": "কন্টেন্ট",
    "categories.Meetup": "মিটআপ",
    "categories.Film": "চলচ্চিত্র",
    "categories.Premiere": "প্রীমিয়ার",
    "event.2.title": "যাত্রা থিয়েটার উৎসব",
    "event.2.description": "যাত্রার প্রাণবন্ত জগতে নিমজ্জিত হন - ঐতিহ্যবাহী লোক থিয়েটার। মাস্টার শিল্পীদের দ্বারা পরিবেশিত আকর্ষণীয় আখ্যানের অভিজ্ঞতা নিন।",
    "event.17.title": "ঐতিহ্যবাহী যাত্রা লোক থিয়েটার",
    "event.17.description": "পৌরাণিক গল্প এবং সামাজিক বিষয়বস্তু সহ ঐতিহ্যবাহী যাত্রা পরিবেশনার সাথে খাঁটি বাঙালি লোক থিয়েটারের অভিজ্ঞতা নিন।",
    "event.33.title": "ক্রিকেট চ্যাম্পিয়নশিপ ফাইনাল",
    "event.33.description": "শহরের ক্রিকেট চ্যাম্পিয়নশিপের রোমাঞ্চকর ফাইনাল লাইভ দেখুন।",
    "event.34.title": "ম্যারাথন রান ২০২৫",
    "event.34.description": "বার্ষিক শহর ম্যারাথনে অংশগ্রহণ করুন এবং ফিটনেস ও স্বাস্থ্যের প্রচার করুন।",
    "event.8.title": "গ্লোবাল আর্টস সামিট - নিউ ইয়র্ক",
    "event.8.description": "আন্তর্জাতিক শিল্পী, কিউরেটর এবং সংস্কৃতি উৎসাহীদের সাথে সংযুক্ত হন। বিশ্বব্যাপী দর্শকদের কাছে আপনার কাজ প্রদর্শন করুন।",
    "event.15.title": "ওডিসি নৃত্য উৎসব",
    "event.15.description": "শাস্ত্রীয় কোরিওগ্রাফি এবং সমসাময়িক ব্যাখ্যা প্রদর্শনকারী মাস্টার পারফরমারদের সাথে ওডিসি নৃত্যের ঐশ্বরিক কৃপা অনুভব করুন।",
    "event.48.title": "ইন্ডিয়ান আইডল কনসার্ট",
    "event.48.description": "এই দর্শনীয় সঙ্গীত কনসার্টে ইন্ডিয়ান আইডল প্রতিযোগীদের লাইভ পারফরম্যান্স দেখুন।",
    "event.22.title": "ওলিউড মিউজিক অ্যাওয়ার্ডস ২০২৫",
    "event.22.description": "ওড়িয়া চলচ্চিত্র সঙ্গীত এবং শিল্পীদের সেরাদের উদযাপনকারী বার্ষিক পুরস্কার অনুষ্ঠান।",
    "event.1.title": "ওডিসি নৃত্য উৎসব ২০২৫",
    "event.1.description": "প্রশংসিত নর্তকদের পরিবেশনার সাথে ওডিসি নৃত্যের কৃপা এবং কমনীয়তা উদযাপন করুন। ঐতিহ্যবাহী কোরিওগ্রাফি এবং সমসাময়িক ব্যাখ্যার অভিজ্ঞতা নিন।",
    "event.12.title": "মাস্টারোর সিতার বাদন",
    "event.12.description": "শাস্ত্রীয় হিন্দুস্তানী সঙ্গীতের এক সন্ধ্যা যেখানে মাস্টারো সিতার বাদক সকাল থেকে রাতের ঐতিহ্য অনুযায়ী রাগ পরিবেশন করবেন।",
    "event.63.title": "ইন্ডিয়ান আইডল শিল্পী পরিবেশনা",
    "event.63.description": "প্রতিভাবান ইন্ডিয়ান আইডল শিল্পীদের লাইভ পরিবেশনার অভিজ্ঞতা নিন যারা তাদের সাঙ্গীতিক যাত্রা প্রদর্শন করবেন।",
    "event.18.title": "ভারতীয় শাস্ত্রীয় সঙ্গীত কনসার্ট",
    "event.18.description": "ভারতীয় শাস্ত্রীয় সঙ্গীতের এক মনমুগ্ধকর সন্ধ্যা যেখানে প্রসিদ্ধ সঙ্গীতজ্ঞরা ঐতিহ্যবাহী রাগ এবং রচনা পরিবেশন করবেন।",
    "event.31.title": "কমেডি ফেস্টিভ্যাল ২০২৫",
    "event.31.description": "ভারতের সেরা কমেডিয়ানদের সাথে তিন দিনের নন-স্টপ হাসি।",
    "event.37.title": "ইউটিউব ক্রিয়েটর সামিট",
    "event.37.description": "সফল ইউটিউবারদের কাছ থেকে মনিটাইজেশন রণনীতি এবং বৃদ্ধির হ্যাক শিখুন।",
    "event.27.title": "সোশ্যাল মিডিয়া ইনফ্লুয়েন্সার সামিট",
    "event.27.description": "শীর্ষ ইনফ্লুয়েন্সারদের সাথে সংযুক্ত হন এবং আপনার সোশ্যাল মিডিয়া উপস্থিতি বাড়ানোর রণনীতি শিখুন।",
    "event.36.title": "ইউটিউবার মিটআপ ২০২৫",
    "event.36.description": "জনপ্রিয় ইউটিউবারদের সাথে দেখা করুন এবং কন্টেন্ট তৈরি ও ভিডিও প্রোডাকশন সম্পর্কে জানুন।",
    "event.49.title": "ইন্ডিয়ান আইডল শিল্পী ফ্যান মিট",
    "event.49.description": "আপনার প্রিয় ইন্ডিয়ান আইডল শিল্পীদের সাথে দেখা করুন, অটোগ্রাফ নিন এবং এই বিশেষ ফ্যান ইভেন্টে ছবি তুলুন।",
    "event.56.title": "ফিউশন মিউজিক নাইট",
    "event.56.description": "প্রতিভাবান বাদ্যযন্ত্রীদের দ্বারা ঐতিহ্যবাহী এবং আধুনিক সঙ্গীতের মিশ্রণের অভিজ্ঞতা নিন।",
    "event.4.title": "ইন্ডি সিনেমা শোকেস ২০২৫",
    "event.4.description": "ভারত এবং বিশ্বের উদীয়মান চলচ্চিত্র নির্মাতাদের স্বতন্ত্র চলচ্চিত্র আবিষ্কার করুন। নির্দেশকদের সাথে প্রশ্নোত্তর সেশন।",
    "event.16.title": "লাইভ সঙ্গীতের সাথে কথক নৃত্য প্রদর্শন",
    "event.16.description": "লাইভ শাস্ত্রীয় সঙ্গীতের সাথে কথক নৃত্যের সৌন্দর্যের অভিজ্ঞতা নিন। মাস্টার নর্তকরা তবলা এবং সিতার সঙ্গতের সাথে ঐতিহ্যবাহী নৃত্যকলা প্রস্তুত করেন।",
    "event.28.title": "ইনফ্লুয়েন্সার মিট অ্যান্ড গ্রীট",
    "event.28.description": "আপনার প্রিয় সোশ্যাল মিডিয়া ইনফ্লুয়েন্সারদের সাথে ব্যক্তিগতভাবে দেখা করুন এবং বিশেষ কন্টেন্ট পান।",
    "event.52.title": "স্ট্রীট থিয়েটার ফেস্টিভ্যাল",
    "event.52.description": "সামাজিক সমস্যাগুলি নিয়ে আকর্ষণীয় স্ট্রীট থিয়েটার প্রদর্শন দেখুন।",
    "event.40.title": "হিপ হপ ডান্স ব্যাটল",
    "event.40.description": "এই উচ্চ শক্তির নৃত্য প্রতিযোগিতায় সেরা হিপ হপ নর্তকদের প্রতিস্পর্ধা দেখুন।",
    "event.54.title": "শাস্ত্রীয় বাদ্যযন্ত্র সঙ্গীত কনসার্ট",
    "event.54.description": "শাস্ত্রীয় সঙ্গীত বাজানো মাস্টার বাদ্যযন্ত্রীদের মন্ত্রমুগ্ধকর প্রদর্শনের আনন্দ নিন।",
    "event.19.title": "ডকুমেন্টারি চলচ্চিত্র উৎসব",
    "event.19.description": "বিশ্বের বিভিন্ন প্রান্ত থেকে পুরস্কার বিজয়ী ডকুমেন্টারির একটি নির্বাচিত সংগ্রহ, যেখানে সংস্কৃতি, সমাজ এবং মানবিক অভিজ্ঞতার গল্প রয়েছে।",
    "event.25.title": "জলিউড স্টার নাইট",
    "event.25.description": "এই বিশেষ ফ্যান মিট এবং বিনোদন রাতে আপনার প্রিয় জলিউড তারকাদের সাথে দেখা করুন।",
    "event.57.title": "জাদু শো এক্সট্রাভ্যাগান্জা",
    "event.57.description": "পেশাদার জাদুকরদের দ্বারা মন চকিত করা জাদুর কারসাজি এবং ভ্রম দেখে বিস্মিত হন।",
    "event.39.title": "সমসাময়িক নৃত্য প্রদর্শন",
    "event.39.description": "পেশাদার নর্তকদের দ্বারা শানদার সমসাময়িক নৃত্য প্রদর্শনের অভিজ্ঞতা নিন।",
    "event.20.title": "আন্তর্জাতিক লঘু চলচ্চিত্র শোকেস",
    "event.20.description": "আন্তর্জাতিক চলচ্চিত্র নির্মাতাদের পুরস্কার বিজয়ী লঘু চলচ্চিত্রের একটি সংগ্রহ, যা বিভিন্ন গল্প বলা এবং উদ্ভাবনী ছবিগ্রহণ প্রদর্শন করে।",
    "event.62.title": "লাইভ রেডিও শো রেকর্ডিং",
    "event.62.description": "জনপ্রিয় আরজে এবং সেলিব্রিটি অতিথিদের সাথে লাইভ রেডিও শো রেকর্ডিংয়ের অংশ হন।",
    "event.21.title": "ওলিউড চলচ্চিত্র প্রীমিয়ার নাইট",
    "event.21.description": "স্টার কাস্ট মিট অ্যান্ড গ্রীটের সাথে সর্বশেষ ওড়িয়া ব্লকবাস্টার চলচ্চিত্রের বিশেষ প্রীমিয়ার।",
    "event.30.title": "স্ট্যান্ড-আপ কমেডি নাইট",
    "event.30.description": "শীর্ষ কমেডিয়ানদের সাথে তাদের সেরা স্ট্যান্ড-আপ রুটিন প্রদর্শন করতে জোরে হাসুন।",
    "event.51.title": "থিয়েটার নাটক - আধুনিক নাটক",
    "event.51.description": "এই সমসাময়িক থিয়েটার প্রদর্শনীর মাধ্যমে শক্তিশালী গল্প বলার অভিজ্ঞতা নিন।",
    "event.24.title": "জলিউড চলচ্চিত্র উৎসব",
    "event.24.description": "পুরস্কার বিজয়ী জলিউড চলচ্চিত্রের স্ক্রিনিংয়ের সাথে ঝাড়খণ্ড সিনেমার উদযাপন করুন।",
    "event.44.title": "সাহিত্য উৎসব ২০২৫",
    "event.44.description": "প্যানেল আলোচনা, বই পাঠ এবং লেখক মতামতের সাথে সাহিত্য উদযাপন করুন।",
    "event.59.title": "আন্তর্জাতিক জাদু উৎসব",
    "event.59.description": "বিশ্বমানের জাদুকরদের অবিশ্বাস্য ভ্রম এবং জাদুর কারসাজি প্রদর্শন দেখুন।",
    "booking.venue": "স্থান",
    "booking.dateTime": "তারিখ ও সময়",
    "booking.ticket": "টিকিট",
    "booking.proceedToPay": "পেমেন্ট করুন",
    "booking.selectVenue": "স্থান নির্বাচন করুন",
    "booking.selectDate": "তারিখ নির্বাচন করুন",
    "booking.selectTime": "সময় নির্বাচন করুন",
    "booking.selectTickets": "টিকিট নির্বাচন করুন",
    "booking.reviewProceed": "পর্যালোচনা করুন ও পেমেন্টে এগিয়ে যান",
    "booking.available": "উপলব্ধ",
    "booking.fastFilling": "দ্রুত ভরে যাচ্ছে",
    "booking.soldOut": "বিক্রি শেষ",
    "booking.proceed": "এগিয়ে যান",
    "booking.general": "সাধারণ",
    "booking.vip": "ভিআইপি",
    "booking.premium": "প্রিমিয়াম",
    "booking.perTicket": "প্রতি টিকিট",
    "booking.mTicket": "এম-টিকিট",
    "booking.savePlanet": "পৃথিবী বাঁচান। আপনার ফোনকে টিকিট হিসেবে ব্যবহার করুন।",
    "booking.mTicketInfo": "এম-টিকিট তথ্য",
    "booking.mTicketPoint1": "১. গ্রাহকরা অ্যাপ/মোবাইল-ওয়েবে 'আমার প্রোফাইল' বিভাগ থেকে তাদের টিকিট অ্যাক্সেস করতে পারেন।",
    "booking.mTicketPoint2": "২. ভেন্যুতে অ্যাপ/মোবাইল-ওয়েবের মাধ্যমে আমার প্রোফাইল বিভাগে টিকিট উপস্থাপন করা বাধ্যতামূলক।",
    "booking.mTicketPoint3": "৩. ভেন্যুতে প্রবেশের জন্য কোন ভৌত টিকিটের প্রয়োজন নেই।",
    "booking.subTotal": "উপ-মোট",
    "booking.bookingFee": "বুকিং ফি",
    "booking.totalAmount": "মোট পরিমাণ",
    "booking.selectState": "রাজ্য নির্বাচন করুন",
    "booking.consent": "এগিয়ে গিয়ে, আমি এই লেনদেন সম্পূর্ণ করার জন্য আমার সম্মতি প্রকাশ করছি।",
    "booking.tickets": "টিকিট",
    "payment.title": "পেমেন্ট",
    "payment.selectMethod": "পেমেন্ট পদ্ধতি নির্বাচন করুন",
    "payment.upi": "ইউপিআই",
    "payment.upiDesc": "ইউপিআই অ্যাপ ব্যবহার করে পেমেন্ট করুন",
    "payment.creditDebit": "ক্রেডিট/ডেবিট কার্ড",
    "payment.cardDesc": "ভিসা, মাস্টারকার্ড, রুপে",
    "payment.netBanking": "নেট ব্যাংকিং",
    "payment.netBankingDesc": "সব প্রধান ব্যাংক সমর্থিত",
    "payment.wallets": "ওয়ালেট",
    "payment.walletsDesc": "পেটিএম, ফোনপে, গুগল পে",
    "payment.bookingSummary": "বুকিং সারসংক্ষেপ",
    "payment.priceBreakdown": "মূল্য বিভাজন",
    "payment.importantInfo": "গুরুত্বপূর্ণ তথ্য:",
    "payment.instantConfirm": "• আপনার বুকিং তাৎক্ষণিকভাবে নিশ্চিত হবে",
    "payment.emailTicket": "• এম-টিকিট আপনার নিবন্ধিত ইমেইলে পাঠানো হবে",
    "payment.idProof": "• অনুগ্রহ করে ভেন্যুতে বৈধ আইডি প্রুফ নিয়ে আসুন",
    "payment.venueGuidelines": "• প্রবেশ ভেন্যু নির্দেশিকা সাপেক্ষে",
    "payment.pay": "পেমেন্ট করুন",
    "payment.date": "তারিখ:",
    "payment.time": "সময়:",
    "payment.venue": "স্থান:",
    "payment.tickets": "টিকিট:",
    "location.Siddeshwari Auditorium, Kolkata, West Bengal": "সিদ্ধেশ্বরী অডিটোরিয়াম, কলকাতা, পশ্চিমবঙ্গ",
    "location.Kolkata": "কলকাতা",
    "location.West Bengal": "পশ্চিমবঙ্গ",
    "location.Bhubaneswar": "ভুবনেশ্বর",
    "location.Virtual": "ভার্চুয়াল",
    "location.Bangalore": "ব্যাঙ্গালোর",
    "location.Delhi": "দিল্লি",
    "location.Mumbai": "মুম্বাই",
    "location.New York": "নিউ ইয়র্ক",
    "location.Chennai": "চেন্নাই",
    "location.Hyderabad": "হায়দরাবাদ",
    "location.Jaipur": "জয়পুর",
    "location.Pune": "পুনে",
    "location.Ahmedabad": "আহমেদাবাদ",
    "location.Odisha": "ওড়িশা",
    "location.Cuttack": "কটক",
    "location.Ranchi": "রাঁচি",
    "terms.title": "সেবার শর্তাবলী",
    "terms.subtitle": "অনুগ্রহ করে এই শর্তগুলি সাবধানে পড়ুন",
    "terms.updated": "সর্বশেষ আপডেট: ডিসেম্বর ২০২৪",
    "terms.section1": "১. শর্তাবলীর স্বীকৃতি",
    "terms.section1.text": "MOOKALAA অ্যাক্সেস এবং ব্যবহার করে, আপনি এই চুক্তির শর্তাবলী এবং বিধানগুলির দ্বারা আবদ্ধ হতে স্বীকার করেন এবং সম্মত হন।",
    "terms.section2": "২. সেবার বিবরণ",
    "terms.section2.text": "MOOKALAA একটি প্ল্যাটফর্ম যা ব্যবহারকারীদের যাত্রা, সিনেমা, সঙ্গীত, নৃত্য, উৎসব, কর্মশালা এবং বিশ্বব্যাপী শিল্পীদের কাস্টম অর্ডার সহ শিল্প ও সাংস্কৃতিক অনুষ্ঠানের সাথে সংযুক্ত করে।",
    "terms.section3": "৩. ব্যবহারকারীর অ্যাকাউন্ট",
    "terms.section3.text": "নির্দিষ্ট বৈশিষ্ট্য অ্যাক্সেস করতে, আপনাকে একটি অ্যাকাউন্ট তৈরি করতে হবে। আপনি নিম্নলিখিতের জন্য দায়ী:",
    "terms.section4": "৪. বুকিং এবং পেমেন্ট",
    "terms.section4.text": "যখন আপনি MOOKALAA এর মাধ্যমে একটি অনুষ্ঠান বুক করেন:",
    "terms.section5": "৫. ব্যবহারকারীর আচরণ",
    "terms.section5.text": "আপনি সম্মত হন যে আপনি নিম্নলিখিত করবেন না:",
    "terms.section6": "৬. অনুষ্ঠান আয়োজক",
    "terms.section6.text": "MOOKALAA ব্যবহারকারী অনুষ্ঠান আয়োজকরা সম্মত হন:",
    "terms.section7": "৭. বুদ্ধিবৃত্তিক সম্পত্তি",
    "terms.section7.text": "MOOKALAA প্ল্যাটফর্ম, এর বিষয়বস্তু, বৈশিষ্ট্য এবং কার্যকারিতা MOOKALAA এর মালিকানাধীন এবং কপিরাইট, ট্রেডমার্ক এবং অন্যান্য বুদ্ধিবৃত্তিক সম্পত্তি আইন দ্বারা সুরক্ষিত।",
    "terms.section8": "৮. দাবি পরিত্যাগ",
    "terms.section8.text": "MOOKALAA প্ল্যাটফর্মটি 'যেমন আছে' কোনো ধরনের ওয়ারেন্টি ছাড়াই প্রদান করে। আমরা কোনো বিষয়বস্তু বা সেবার নির্ভুলতা, সম্পূর্ণতা বা নির্ভরযোগ্যতার গ্যারান্টি দিই না।",
    "terms.section9": "৯. দায়বদ্ধতার সীমা",
    "terms.section9.text": "MOOKALAA আপনার সেবা ব্যবহারের ফলে উদ্ভূত কোনো পরোক্ষ, আকস্মিক, বিশেষ, পরিণামী বা শাস্তিমূলক ক্ষতির জন্য দায়বদ্ধ থাকবে না।",
    "terms.section10": "১০. সমাপ্তি",
    "terms.section10.text": "আমরা আমাদের একক বিবেচনায়, পূর্ব নোটিশ ছাড়াই, আপনার অ্যাকাউন্ট এবং সেবায় অ্যাক্সেস বন্ধ বা স্থগিত করতে পারি, এমন আচরণের জন্য যা আমাদের মতে এই শর্তাবলী লঙ্ঘন করে।",
    "terms.section11": "১১. শর্তাবলীতে পরিবর্তন",
    "terms.section11.text": "আমরা যেকোনো সময় এই শর্তাবলী সংশোধন করার অধিকার সংরক্ষণ করি। আমরা ইমেইল বা প্ল্যাটফর্মের মাধ্যমে ব্যবহারকারীদের কোনো গুরুত্বপূর্ণ পরিবর্তনের বিজ্ঞপ্তি দেব।",
    "terms.section12": "১২. যোগাযোগের তথ্য",
    "terms.section12.text": "এই সেবার শর্তাবলী সম্পর্কে আপনার কোনো প্রশ্ন থাকলে, অনুগ্রহ করে আমাদের সাথে যোগাযোগ করুন:",
    "terms.bullet3.1": "আপনার অ্যাকাউন্ট প্রমাণপত্রের গোপনীয়তা বজায় রাখা",
    "terms.bullet3.2": "আপনার অ্যাকাউন্টের অধীনে ঘটে যাওয়া সমস্ত কার্যকলাপ",
    "terms.bullet3.3": "নির্ভুল এবং সম্পূর্ণ তথ্য প্রদান করা",
    "terms.bullet3.4": "প্রয়োজন অনুযায়ী আপনার তথ্য আপডেট করা",
    "terms.bullet4.1": "আপনি সমস্ত প্রযোজ্য ফি প্রদান করতে সম্মত হন",
    "terms.bullet4.2": "পেমেন্ট তৃতীয় পক্ষের প্রদানকারীদের মাধ্যমে নিরাপদে প্রক্রিয়া করা হয়",
    "terms.bullet4.3": "বুকিং নিশ্চিতকরণ অনুষ্ঠান আয়োজকের অনুমোদনের সাপেক্ষে",
    "terms.bullet4.4": "বাতিলকরণ নীতি অনুষ্ঠান এবং আয়োজক অনুযায়ী ভিন্ন হয়",
    "terms.bullet5.1": "কোনো বেআইনি উদ্দেশ্যে সেবা ব্যবহার করা",
    "terms.bullet5.2": "সেবায় হস্তক্ষেপ করা বা ব্যাহত করা",
    "terms.bullet5.3": "ক্ষতিকারক বা দূষিত বিষয়বস্তু আপলোড করা",
    "terms.bullet5.4": "কোনো প্রযোজ্য আইন বা নিয়মকানুন লঙ্ঘন করা",
    "terms.bullet5.5": "বুদ্ধিবৃত্তিক সম্পত্তির অধিকার লঙ্ঘন করা",
    "terms.bullet6.1": "নির্ভুল অনুষ্ঠানের তথ্য প্রদান করা",
    "terms.bullet6.2": "নিশ্চিত বুকিংয়ের সম্মান করা",
    "terms.bullet6.3": "প্রযোজ্য আইন ও নিয়মকানুন মেনে চলা",
    "terms.bullet6.4": "উপযুক্ত বীমা কভারেজ বজায় রাখা",
    "privacy.title": "গোপনীয়তা নীতি",
    "privacy.subtitle": "আপনার গোপনীয়তা আমাদের কাছে গুরুত্বপূর্ণ",
    "privacy.updated": "সর্বশেষ আপডেট: ডিসেম্বর ২০২৪",
    "privacy.section1": "১. আমরা যে তথ্য সংগ্রহ করি",
    "privacy.section1.text": "MOOKALAA তে, আমরা সেই তথ্য সংগ্রহ করি যা আপনি সরাসরি আমাদের প্রদান করেন, যেমন যখন আপনি অ্যাকাউন্ট তৈরি করেন, অনুষ্ঠান বুক করেন, বা সহায়তার জন্য আমাদের সাথে যোগাযোগ করেন।",
    "privacy.section2": "২. আমরা কীভাবে আপনার তথ্য ব্যবহার করি",
    "privacy.section2.text": "আমরা সংগৃহীত তথ্য নিম্নলিখিতের জন্য ব্যবহার করি:",
    "privacy.section3": "৩. তথ্য ভাগাভাগি",
    "privacy.section3.text1": "আমরা আপনার সম্মতি ছাড়া আপনার ব্যক্তিগত তথ্য তৃতীয় পক্ষের কাছে বিক্রি, ব্যবসা বা স্থানান্তর করি না, এই নীতিতে বর্ণিত ব্যতীত।",
    "privacy.section3.text2": "আমরা আপনার তথ্য নিম্নলিখিতদের সাথে ভাগ করতে পারি:",
    "privacy.section4": "৪. ডেটা নিরাপত্তা",
    "privacy.section4.text": "আমরা আপনার ব্যক্তিগত তথ্যকে অননুমোদিত অ্যাক্সেস, পরিবর্তন, প্রকাশ বা ধ্বংস থেকে রক্ষা করার জন্য উপযুক্ত নিরাপত্তা ব্যবস্থা বাস্তবায়ন করি।",
    "privacy.section5": "৫. আপনার অধিকার",
    "privacy.section5.text": "আপনার নিম্নলিখিত অধিকার রয়েছে:",
    "privacy.section6": "৬. কুকিজ এবং ট্র্যাকিং",
    "privacy.section6.text": "আমরা আপনার অভিজ্ঞতা বৃদ্ধি, ব্যবহার বিশ্লেষণ এবং ব্যক্তিগতকৃত বিষয়বস্তু প্রদানের জন্য কুকিজ এবং অনুরূপ প্রযুক্তি ব্যবহার করি।",
    "privacy.section7": "৭. আমাদের সাথে যোগাযোগ করুন",
    "privacy.section7.text": "এই গোপনীয়তা নীতি সম্পর্কে আপনার কোনো প্রশ্ন থাকলে, অনুগ্রহ করে আমাদের সাথে যোগাযোগ করুন:",
    "privacy.bullet1.1": "ব্যক্তিগত তথ্য (নাম, ইমেইল, ফোন নম্বর)",
    "privacy.bullet1.2": "পেমেন্ট তথ্য (তৃতীয় পক্ষের প্রদানকারীদের মাধ্যমে নিরাপদে প্রক্রিয়াকৃত)",
    "privacy.bullet1.3": "অনুষ্ঠানের পছন্দ এবং বুকিং ইতিহাস",
    "privacy.bullet1.4": "যোগাযোগের পছন্দ",
    "privacy.bullet2.1": "আমাদের সেবা প্রদান এবং উন্নতি করা",
    "privacy.bullet2.2": "বুকিং এবং পেমেন্ট প্রক্রিয়া করা",
    "privacy.bullet2.3": "আপনাকে অনুষ্ঠানের সুপারিশ এবং আপডেট পাঠানো",
    "privacy.bullet2.4": "গ্রাহক সহায়তা প্রদান করা",
    "privacy.bullet2.5": "আইনি বাধ্যবাধকতা মেনে চলা",
    "privacy.bullet3.1": "অনুষ্ঠান আয়োজক (শুধুমাত্র প্রয়োজনীয় বুকিং বিবরণ)",
    "privacy.bullet3.2": "লেনদেন প্রক্রিয়াকরণের জন্য পেমেন্ট প্রসেসর",
    "privacy.bullet3.3": "সেবা প্রদানকারী যারা আমাদের কার্যক্রমে সহায়তা করে",
    "privacy.bullet3.4": "আইন দ্বারা প্রয়োজন হলে আইনি কর্তৃপক্ষ",
    "privacy.bullet5.1": "আপনার ব্যক্তিগত তথ্য অ্যাক্সেস করুন",
    "privacy.bullet5.2": "ভুল তথ্য সংশোধন করুন",
    "privacy.bullet5.3": "আপনার অ্যাকাউন্ট এবং ব্যক্তিগত তথ্য মুছুন",
    "privacy.bullet5.4": "মার্কেটিং যোগাযোগ থেকে অপ্ট-আউট করুন",
    "privacy.bullet5.5": "ডেটা পোর্টেবিলিটি",
    "eventDetail.notFound": "অনুষ্ঠান পাওয়া যায়নি",
    "eventDetail.backToEvents": "অনুষ্ঠানে ফিরে যান",
    "eventDetail.date": "তারিখ",
    "eventDetail.time": "সময়",
    "eventDetail.location": "অবস্থান",
    "eventDetail.attending": "উপস্থিত",
    "eventDetail.addToCalendar": "ক্যালেন্ডারে যোগ করুন",
    "eventDetail.aboutOrganizer": "আয়োজক সম্পর্কে",
    "eventDetail.relatedEvents": "সম্পর্কিত অনুষ্ঠান",
    "eventDetail.eventInfo": "অনুষ্ঠানের তথ্য",
    "eventDetail.entryFee": "প্রবেশ ফি",
    "eventDetail.eventType": "অনুষ্ঠানের ধরন",
    "eventDetail.onlineEvent": "অনলাইন অনুষ্ঠান",
    "eventDetail.inPerson": "ব্যক্তিগতভাবে",
    "eventDetail.attendees": "উপস্থিত ব্যক্তিরা",
    "eventDetail.markInterested": "আগ্রহী হিসেবে চিহ্নিত করুন",
    "eventDetail.shareEvent": "অনুষ্ঠান শেয়ার করুন",
    "eventDetail.tags": "ট্যাগ",
    "eventDetail.bookTicket": "টিকিট বুক করুন",
    "trending.title": "ট্রেন্ডিং শহর",
    "trending.subtitle": "জনপ্রিয় গন্তব্যে অনুষ্ঠান অন্বেষণ করুন",
    "trending.events": "অনুষ্ঠান",
    "eventsPage.title": "অনুষ্ঠান আবিষ্কার করুন",
    "eventsPage.found": "পাওয়া গেছে",
    "eventsPage.events": "অনুষ্ঠান",
    "eventsPage.gridView": "গ্রিড ভিউ",
    "eventsPage.mapView": "ম্যাপ ভিউ",
    "eventsPage.sortPopular": "সবচেয়ে জনপ্রিয়",
    "eventsPage.sortDate": "নিকটতম তারিখ",
    "eventsPage.sortRecent": "সম্প্রতি যোগ করা হয়েছে",
    "booking.selectOptions": "অনুগ্রহ করে নিম্নলিখিত বিকল্প(গুলি) থেকে নির্বাচন করুন",
    "booking.dateLabel": "রবি",
    "booking.viewMaps": "ম্যাপে দেখুন",
    "booking.location": "অবস্থান",
    "booking.venue": "স্থান",
    "booking.proceed": "এগিয়ে যান",
    "organizer.Odissi Classical Arts": "ওডিসি শাস্ত্রীয় কলা",
    "organizer.Global Jatra Collective": "গ্লোবাল যাত্রা কালেক্টিভ",
    "organizer.MOOKALAA Artists Network": "MOOKALAA শিল্পী নেটওয়ার্ক",
    "organizer.Dance India Movement": "ডান্স ইন্ডিয়া মুভমেন্ট",
    "event.book-launch.title": "বই লঞ্চ ও লেখক সাক্ষাৎ",
    "event.book-launch.description": "বেস্টসেলিং লেখকদের সাথে দেখা করুন এবং এই একচেটিয়া বই লঞ্চ ইভেন্টে আপনার বই সাইন করান।",
    "event.content-creator-workshop.title": "কন্টেন্ট ক্রিয়েটর ওয়ার্কশপ",
    "event.content-creator-workshop.description": "সফল ইনফ্লুয়েন্সার এবং ক্রিয়েটরদের কাছ থেকে কন্টেন্ট তৈরির টিপস এবং কৌশল শিখুন।",
    "event.rj-meet-greet.title": "আরজে মিট অ্যান্ড গ্রিট",
    "event.rj-meet-greet.description": "আপনার প্রিয় রেডিও জকিদের সাথে দেখা করুন এবং রেডিও সম্প্রচারের জগত সম্পর্কে জানুন।",
    "event.video-editing-workshop.title": "ইউটিউবারদের দ্বারা ভিডিও এডিটিং ওয়ার্কশপ",
    "event.video-editing-workshop.description": "পেশাদার ইউটিউবারদের কাছ থেকে ভিডিও এডিটিং কৌশল আয়ত্ত করুন।",
    "event.jollywood-filmmaking-workshop.title": "জলিউড চলচ্চিত্র নির্মাণ ওয়ার্কশপ",
    "event.jollywood-filmmaking-workshop.description": "অভিজ্ঞ জলিউড পরিচালক এবং চিত্রগ্রাহকদের কাছ থেকে চলচ্চিত্র নির্মাণের শিল্প শিখুন।"
  },
  brx: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "hero.subtitle": "Unite Through Arts - Find Jatra, Cinema, Music, Dance & More",
    "explore": "Explore Events"
  },
  doi: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "hero.subtitle": "Unite Through Arts - Find Jatra, Cinema, Music, Dance & More",
    "explore": "Explore Events"
  },
  gu: {
    "hero.title": "અદ્ભુત કલા અને સાંસ્કૃતિક કાર્યક્રમો શોધો",
    "hero.subtitle": "કલાના માધ્યમથી એકજુટ થઆઓ - યાત્રા, સિનેમા, સંગીત, નૃત્ય અને વધુ શોધો",
    "explore": "કાર્યક્રમો અન્વેષણ કરો"
  },
  kn: {
    "hero.title": "ಅದ್ಭುತ ಕಲೆ ಮತ್ತು ಸಾಂಸ್ಕೃತಿಕ ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಅನ್ವೇಷಿಸಿ",
    "explore": "ಕಾರ್ಯಕ್ರಮಗಳನ್ನು ಅನ್ವೇಷಿಸಿ"
  },
  ks: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "explore": "Explore Events"
  },
  gom: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "explore": "Explore Events"
  },
  mai: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "explore": "Explore Events"
  },
  ml: {
    "hero.title": "അത്ഭുതകരമായ കലാ സാംസ്കാരിക പരിപാടികൾ കണ്ടെത്തുക",
    "explore": "പരിപാടികൾ പര്യവേക്ഷണം ചെയ്യുക"
  },
  mni: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "explore": "Explore Events"
  },
  mr: {
    "hero.title": "आश्चर्यकारक कला आणि सांस्कृतिक कार्यक्रम शोधा",
    "explore": "कार्यक्रम एक्सप्लोर करा"
  },
  ne: {
    "hero.title": "अद्भुत कला र सांस्कृतिक कार्यक्रमहरू पत्ता लगाउनुहोस्",
    "explore": "कार्यक्रमहरू अन्वेषण गर्नुहोस्"
  },
  or: {
    "hero.title": "ଅଦ୍ଭୁତ କଳା ଏବଂ ସାଂସ୍କୃତିକ କାର୍ଯ୍ୟକ୍ରମ ଆବିଷ୍କାର କରନ୍ତୁ",
    "explore": "କାର୍ଯ୍ୟକ୍ରମ ଅନୁସନ୍ଧାନ କରନ୍ତୁ"
  },
  pa: {
    "hero.title": "ਸ਼ਾਨਦਾਰ ਕਲਾ ਅਤੇ ਸੱਭਿਆਚਾਰਕ ਸਮਾਗਮਾਂ ਦੀ ਖੋਜ ਕਰੋ",
    "explore": "ਸਮਾਗਮਾਂ ਦੀ ਖੋਜ ਕਰੋ"
  },
  sa: {
    "hero.title": "आश्चर्यजनकं कलां सांस्कृतिकं कार्यक्रमाणि च अन्वेषयतु",
    "explore": "कार्यक्रमाणि अन्वेषयतु"
  },
  sat: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "explore": "Explore Events"
  },
  sd: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "explore": "Explore Events"
  },
  ta: {
    "hero.title": "அற்புதமான கலை மற்றும் கலாச்சார நிகழ்வுகளைக் கண்டறியுங்கள்",
    "explore": "நிகழ்வுகளை ஆராயுங்கள்"
  },
  te: {
    "hero.title": "అద్భుతమైన కళలు మరియు సాంస్కృతిక కార్యక్రమాలను కనుగొనండి",
    "explore": "కార్యక్రమాలను అన్వేషించండి"
  },
  ur: {
    "hero.title": "حیرت انگیز فنون اور ثقافتی تقریبات دریافت کریں",
    "explore": "تقریبات کی تلاش کریں"
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  const translateCategory = (category: string): string => {
    return t(`categories.${category}`)
  }

  const translateEvent = (eventId: string, field: 'title' | 'description', defaultValue: string): string => {
    const key = `event.${eventId}.${field}`
    const translated = translations[language][key as keyof typeof translations.en]
    return translated || defaultValue
  }

  const translateOrganizer = (organizerName: string): string => {
    const key = `organizer.${organizerName}`
    const translated = translations[language][key as keyof typeof translations.en]
    return translated || organizerName
  }

  const translateLocation = (location: string): string => {
    if (language === 'en') return location
    
    // Translation map for location parts
    const locationMap: { [key: string]: string } = {
      'Bhubaneswar': language === 'hi' ? 'भुवनेश्वर' : 'ভুবনেশ্বর',
      'Kolkata': language === 'hi' ? 'कोलकाता' : 'কলকাতা',
      'Virtual': language === 'hi' ? 'वर्चुअल' : 'ভার্চুয়াল',
      'Bangalore': language === 'hi' ? 'बैंगलोर' : 'ব্যাঙ্গালোর',
      'Delhi': language === 'hi' ? 'दिल्ली' : 'দিল্লি',
      'Mumbai': language === 'hi' ? 'मुंबई' : 'মুম্বাই',
      'New York': language === 'hi' ? 'न्यूयॉर्क' : 'নিউ ইয়র্ক',
      'Chennai': language === 'hi' ? 'चेन्नई' : 'চেন্নাই',
      'Hyderabad': language === 'hi' ? 'हैदराबाद' : 'হায়দরাবাদ',
      'Jaipur': language === 'hi' ? 'जयपुर' : 'জয়পুর',
      'Pune': language === 'hi' ? 'पुणे' : 'পুনে',
      'Ahmedabad': language === 'hi' ? 'अहमदाबाद' : 'আহমেদাবাদ',
      'Odisha': language === 'hi' ? 'ओडिशा' : 'ওড়িশা',
      'Cuttack': language === 'hi' ? 'कटक' : 'কটক',
      'Ranchi': language === 'hi' ? 'रांची' : 'রাঁচি',
      'West Bengal': language === 'hi' ? 'पश्चिम बंगाल' : 'পশ্চিমবঙ্গ',
      'Karnataka': language === 'hi' ? 'कर्नाटक' : 'কর্ণাটক',
      'India': language === 'hi' ? 'भारत' : 'ভারত',
      'Maharashtra': language === 'hi' ? 'महाराष्ट्र' : 'মহারাষ্ট্র',
      'Tamil Nadu': language === 'hi' ? 'तमिलनाडु' : 'তামিলনাড়ু',
      'Telangana': language === 'hi' ? 'तेलंगाना' : 'তেলেঙ্গানা',
      'Rajasthan': language === 'hi' ? 'राजस्थान' : 'রাজস্থান',
      'Gujarat': language === 'hi' ? 'गुजरात' : 'গুজরাট',
      'Jharkhand': language === 'hi' ? 'झारखंड' : 'ঝাড়খণ্ড',
      'USA': language === 'hi' ? 'यूएसए' : 'ইউএসএ',
      'Online': language === 'hi' ? 'ऑनलाइन' : 'অনলাইন',
      'Odissi': language === 'hi' ? 'ओडिसी' : 'ওডিসি',
      'Street Arena': language === 'hi' ? 'स्ट्रीट एरिना' : 'স্ট্রিট এরিনা',
      'Arena': language === 'hi' ? 'एरिना' : 'এরিনা',
      'Street': language === 'hi' ? 'स्ट्रीट' : 'স্ট্রিট',
      'Hall': language === 'hi' ? 'हॉल' : 'হল',
      'Center': language === 'hi' ? 'सेंटर' : 'সেন্টার',
      'Centre': language === 'hi' ? 'सेंटर' : 'সেন্টার',
      'Stadium': language === 'hi' ? 'स्टेडियम' : 'স্টেডিয়াম',
      'Park': language === 'hi' ? 'पार्क' : 'পার্ক',
      'Garden': language === 'hi' ? 'गार्डन' : 'গার্ডেন',
      'Auditorium': language === 'hi' ? 'ऑडिटोरियम' : 'অডিটোরিয়াম',
      'Theatre': language === 'hi' ? 'थिएटर' : 'থিয়েটার',
      'Theater': language === 'hi' ? 'थिएटर' : 'থিয়েটার',
      'Club': language === 'hi' ? 'क्लब' : 'ক্লাব',
      'Hotel': language === 'hi' ? 'होटल' : 'হোটেল',
      'Resort': language === 'hi' ? 'रिसॉर्ट' : 'রিসোর্ট',
      'Mall': language === 'hi' ? 'मॉल' : 'মল',
      'Complex': language === 'hi' ? 'कॉम्प्लेक्स' : 'কমপ্লেক্স'
    }
    
    // Replace each part of the location (case-insensitive)
    let translatedLocation = location
    Object.keys(locationMap).forEach(key => {
      const regex = new RegExp(key, 'gi')
      translatedLocation = translatedLocation.replace(regex, locationMap[key])
    })
    
    return translatedLocation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateCategory, translateEvent, translateOrganizer, translateLocation }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    return {
      language: "en" as Language,
      setLanguage: () => {},
      t: (key: string) => key,
      translateCategory: (category: string) => category,
      translateEvent: (eventId: string, field: 'title' | 'description', defaultValue: string) => defaultValue,
      translateOrganizer: (organizerName: string) => organizerName,
      translateLocation: (location: string) => location
    }
  }
  return context
}
