import type { Event, EventCity, Organizer } from "./types"
import { translateEventTime, translateEventLocation, translateEventTags } from "./event-translations"

export const categories = ["Jatra", "Cinema", "Ollywood", "Jollywood", "Music", "Influencer", "Comedian", "Sports", "YouTuber's", "Dancer", "Authors", "Poet", "Theatre Artists", "Instrumentalist", "Magician", "RJ", "Indian idol Artist"]

export const featuredArtist = {
  name: "Sunny Hindustani",
  title: "Indian Idol Star",
  description: "A rising star from Indian Idol with exceptional vocal range and stage presence. Known for his versatile singing style and ability to connect with audiences through his performances.",
  image: "/placeholder-user.jpg",
  rating: 4.9,
  followers: "125K",
  performances: [
    "/indian-classical-music-masterclass.jpg",
    "/concert-stage-lights-event.jpg",
    "/bollywood-singer-recording-studio.jpg",
    "/sitar-recital-classical-music.jpg",
    "/global-arts-summit-networking.jpg"
  ]
}

export const trendingCities: EventCity[] = [
  {
    name: "Odisha",
    country: "Odisha, India",
    eventCount: 445,
    image: "/image.png",
    coordinates: { lat: 20.2961, lng: 85.8245 },
  },
  {
    name: "Bhubaneswar",
    country: "Odissi, India",
    eventCount: 245,
    image: "/lingaraj-temple-bhubaneshwar-odisha-2-attr-hero.jpg",
    coordinates: { lat: 20.2961, lng: 85.8245 },
  },
  {
    name: "Delhi",
    country: "India",
    eventCount: 892,
    image: "/delhi-india-cultural-hub.jpg",
    coordinates: { lat: 28.7041, lng: 77.1025 },
  },
  {
    name: "Mumbai",
    country: "India",
    eventCount: 756,
    image: "/mumbai-india-arts-scene.jpg",
    coordinates: { lat: 19.076, lng: 72.8777 },
  },
  {
    name: "Kolkata",
    country: "India",
    eventCount: 634,
    image: "/kolkata-india-cultural-capital.jpg",
    coordinates: { lat: 22.5726, lng: 88.3639 },
  },
  {
    name: "Bangalore",
    country: "India",
    eventCount: 521,
    image: "/bangalore-india-tech-arts-fusion.jpg",
    coordinates: { lat: 12.9716, lng: 77.5946 },
  },

]

const organizers: Organizer[] = [
  {
    id: "1",
    name: "Odissi Classical Arts",
    image: "/bharatanatyam-dance-workshop.jpg",
    verified: true,
    events: 42,
    followers: 5200,
  },
  {
    id: "2",
    name: "Global Jatra Collective",
    image: "/jatra-theatre-logo.jpg",
    verified: true,
    events: 28,
    followers: 8400,
  },
  {
    id: "3",
    name: "Dance India Movement",
    image: "/dance-arts-logo.jpg",
    verified: true,
    events: 15,
    followers: 2100,
  },
  {
    id: "4",
    name: "MOOKALAA Artists Network",
    image: "/mookalaa-platform-logo.jpg",
    verified: true,
    events: 54,
    followers: 12000,
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Odissi Dance Festival 2025",
    description:
      "Celebrate the grace and elegance of Odissi dance with performances from acclaimed dancers. Experience traditional choreography and contemporary interpretations.",
    image: "/odissi-dance-festival-performance-stage.jpg",
    date: new Date("2025-02-15"),
    time: "06:00 PM",
    endDate: new Date("2025-02-15"),
    location: "Rabindra Mandap, Bhubaneswar, Odissi",
    city: "Bhubaneswar",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Dance",
    price: 299,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 2341,
    tags: ["Odissi", "Dance", "Classical", "Traditional Art"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "2",
    title: "Jatra Theatre Festival",
    description:
      "Immerse yourself in the vibrant world of Jatra - traditional folk theatre. Experience compelling narratives performed by master artists.",
    image: "/jatra-traditional-theatre-performance.jpg",
    hoverVideo: "/video/Video_Generation_Complete.mp4",
    date: new Date("2025-02-22"),
    time: "07:00 PM",
    endDate: new Date("2025-02-24"),
    location: "Siddeshwari Auditorium, Kolkata, West Bengal",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Jatra",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 5234,
    tags: ["Jatra", "Theatre", "Folk Art", "Traditional"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "3",
    title: "Learn Kathak Dance Online",
    description:
      "Master the fundamentals of Kathak dance in this comprehensive online workshop. Learn from Kathak maestro with personalized feedback.",
    image: "/kathak-dance-online-workshop.jpg",
    date: new Date("2025-02-10"),
    time: "06:00 PM",
    endDate: new Date("2025-03-10"),
    location: "Online",
    city: "Virtual",
    coordinates: { lat: 0, lng: 0 },
    category: "Workshops",
    price: 0,
    isFree: true,
    isOnline: true,
    organizer: organizers[2],
    attendees: 1234,
    tags: ["Kathak", "Dance", "Online", "Workshop"],
    rating: 4.5,
  },
  {
    id: "4",
    title: "India Cinema Showcase 2025",
    description:
      "Discover independent films from emerging filmmakers across India and the world. Q&A sessions with directors.",
    image: "/film-festival-cinema-screening.jpg",
    hoverVideo: "/video/Make_a_video_202512011735_ksfvw.mp4",
    date: new Date("2025-03-01"),
    time: "02:00 PM",
    endDate: new Date("2025-03-03"),
    location: "PVR Cinemas, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Cinema",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 892,
    tags: ["Cinema", "Indie Films", "Festival", "Documentary"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "5",
    title: "Custom Personalized Song from Bollywood Artists",
    description:
      "Commission a personalized song, birthday greeting, or special message from professional Bollywood singers. Perfect for celebrations!",
    image: "/bollywood-singer-recording-studio.jpg",
    date: new Date("2025-03-15"),
    time: "12:00 PM",
    location: "Online - Delivery",
    city: "Virtual",
    coordinates: { lat: 0, lng: 0 },
    category: "Custom Orders",
    price: 499, 
    isFree: false,
    isOnline: true,
    organizer: organizers[0],
    attendees: 234,
    tags: ["Custom Order", "Music", "Bollywood", "Gift"],
    rating: 4.6,
  },
  {
    id: "6",
    title: "Holi Festival - Music & Dance Celebration",
    description:
      "Celebrate the festival of colors with live music performances, traditional dances, and cultural celebrations.",
    image: "/holi-festival-celebration.jpg",
    date: new Date("2025-03-10"),
    time: "04:00 PM",
    location: "Cultural Centre, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Festivals",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[3],
    attendees: 89,
    tags: ["Holi", "Festival", "Music", "Culture"],
    rating: 4.4,
  },
  {
    id: "7",
    title: "Indian Classical Music Masterclass",
    description:
      "Learn Indian classical music from Grammy-nominated musician. Cover raag theory, instrument techniques, and composition.",
    image: "/indian-classical-music-masterclass.jpg",
    date: new Date("2025-02-28"),
    time: "10:00 AM",
    location: "Ravindra Sarovar, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Workshops",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1567,
    tags: ["Classical Music", "Masterclass", "Learning", "Workshop"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "8",
    title: "Global Arts Summit - New York",
    description:
      "Connect with international artists, curators, and culture enthusiasts. Showcase your work to a global audience.",
    image: "/global-arts-summit-networking.jpg",
    date: new Date("2025-03-20"),
    time: "09:00 AM",
    endDate: new Date("2025-03-22"),
    location: "Lincoln Center, New York, USA",
    city: "New York",
    coordinates: { lat: 40.7128, lng: -74.006 },
    category: "Festivals",
    price: 799,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 3456,
    tags: ["Global", "Summit", "Arts", "Networking"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "9",
    title: "Bharatanatyam Dance Workshop for Beginners",
    description:
      "Learn the classical South Indian dance form Bharatanatyam from experienced instructors. Perfect for beginners with no prior experience.",
    image: "/bharatanatyam-dance-workshop.jpg",
    date: new Date("2025-02-20"),
    time: "05:00 PM",
    location: "Arts Academy, Chennai, Tamil Nadu",
    city: "Chennai",
    coordinates: { lat: 13.0827, lng: 80.2707 },
    category: "Workshops",
    price: 149,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 456,
    tags: ["Bharatanatyam", "Dance", "Beginners", "Classical"],
    rating: 4.6,
  },
  {
    id: "10",
    title: "Digital Art & Animation Expo",
    description:
      "Showcase digital artworks, animations, and interactive installations from emerging digital artists. Networking with tech & art professionals.",
    image: "/digital-art-animation-expo.jpg",
    date: new Date("2025-03-08"),
    time: "11:00 AM",
    endDate: new Date("2025-03-10"),
    location: "Tech Hub, Hyderabad, Telangana",
    city: "Hyderabad",
    coordinates: { lat: 17.385, lng: 78.4867 },
    category: "Festivals",
    price: 250,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 1234,
    tags: ["Digital Art", "Animation", "Expo", "Technology"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "11",
    title: "Traditional Puppet Theater Show - Kathputli",
    description:
      "Experience the ancient art of Kathputli puppet theater with live performances depicting traditional Indian folklore and mythology.",
    image: "/kathputli-puppet-theater-show.jpg",
    date: new Date("2025-02-25"),
    time: "07:30 PM",
    location: "Heritage Theater, Jaipur, Rajasthan",
    city: "Jaipur",
    coordinates: { lat: 26.9124, lng: 75.7873 },
    category: "Festivals",
    price: 175,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 678,
    tags: ["Kathputli", "Puppet Theater", "Traditional", "Folklore"],
    rating: 4.5,
  },
  {
    id: "12",
    title: "Sitar Recital by Maestro",
    description:
      "An evening of classical Hindustani music featuring maestro sitar player performing raags from morning to night traditions.",
    image: "/sitar-recital-classical-music.jpg",
    hoverVideo: "/video/Make_a_video_202512011730_djvk7.mp4",
    date: new Date("2025-03-05"),
    time: "06:00 PM",
    location: "Sapru House, New Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.6129, lng: 77.201 },
    category: "Music",
    price: 399,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 2100,
    tags: ["Sitar", "Classical", "Hindustani Music", "Maestro"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "13",
    title: "Street Art & Graffiti Workshop",
    description:
      "Learn urban art and graffiti techniques from professional street artists. Create your own mural with proper guidance and safety.",
    image: "/street-art-graffiti-workshop.jpg",
    date: new Date("2025-03-12"),
    time: "02:00 PM",
    location: "Art District, Pune, Maharashtra",
    city: "Pune",
    coordinates: { lat: 18.5204, lng: 73.8567 },
    category: "Workshops",
    price: 299,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 321,
    tags: ["Street Art", "Graffiti", "Workshop", "Urban Art"],
    rating: 4.4,
  },
  {
    id: "14",
    title: "Photography Exhibition - Faces of India",
    description:
      "A powerful photography exhibition showcasing portraits and stories of ordinary people from across India. Interactive artist talks.",
    image: "/photography-exhibition-faces-of-india.jpg",
    date: new Date("2025-03-16"),
    time: "10:00 AM",
    endDate: new Date("2025-03-25"),
    location: "Gallery Central, Ahmedabad, Gujarat",
    city: "Ahmedabad",
    coordinates: { lat: 23.0225, lng: 72.5714 },
    category: "Festivals",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1890,
    tags: ["Photography", "Exhibition", "Portrait", "Art"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "15",
    title: "Odissi Dance Festival",
    description:
      "Experience the divine grace of Odissi dance with master performers showcasing classical choreography and contemporary interpretations.",
    image: "/odissi-dance-festival-performance-stage.jpg",
    hoverVideo: "/video/1764583058940.mp4",
    date: new Date("2025-02-26"),
    time: "07:00 PM",
    endDate: new Date("2025-02-28"),
    location: "Kalinga Stadium, Bhubaneswar, Odissi",
    city: "Odisha",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Jatra",
    price: 450,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 3200,
    tags: ["Odissi", "Dance", "Classical", "Heritage"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "16",
    title: "Kathak Dance Performance with Live Music",
    description:
      "Experience the elegance of Kathak dance accompanied by live classical music. Master dancers perform traditional choreography with tabla and sitar accompaniment.",
    image: "/kathak-dance-online-workshop.jpg",
    hoverVideo: "/video/Video_Generation_Complete-222.mp4",
    date: new Date("2025-03-08"),
    time: "07:30 PM",
    location: "Music Academy, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Music",
    price: 275,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 850,
    tags: ["Kathak", "Dance", "Classical Music", "Live Performance"],
    featured: true,
    rating: 4.7,
  },
  {
    id: "17",
    title: "Traditional Jatra Folk Theatre",
    description:
      "Experience authentic Bengali folk theatre with traditional Jatra performances featuring mythological stories and social themes.",
    image: "/37ce720301ab1ec46d70699242db169c.jpg",
    hoverVideo: "/video/Make_a_video_202512011800_y1a4q.mp4",
    date: new Date("2025-03-12"),
    time: "08:00 PM",
    location: "Folk Theatre Hall, Kolkata, West Bengal",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Jatra",
    price: 180,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 1200,
    tags: ["Jatra", "Folk Theatre", "Bengali", "Traditional"],
    featured: true,
    rating: 4.6,
  },
  {
    id: "18",
    title: "Indian Classical Music Concert",
    description:
      "An enchanting evening of Indian classical music featuring renowned musicians performing traditional ragas and compositions.",
    image: "/indian-classical-music-masterclass.jpg",
    hoverVideo: "/video/Make_a_video_202512011729_o133i.mp4",
    date: new Date("2025-03-15"),
    time: "07:00 PM",
    location: "Music Auditorium, Chennai, Tamil Nadu",
    city: "Chennai",
    coordinates: { lat: 13.0827, lng: 80.2707 },
    category: "Music",
    price: 320,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1500,
    tags: ["Classical Music", "Concert", "Ragas", "Traditional"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "19",
    title: "Documentary Film Festival",
    description:
      "A curated selection of award-winning documentaries from around the world, featuring stories of culture, society, and human experiences.",
    image: "/digital-art-animation-expo.jpg",
    hoverVideo: "/video/Make_a_video_202512011727_ikc3b.mp4",
    date: new Date("2025-03-18"),
    time: "06:00 PM",
    endDate: new Date("2025-03-20"),
    location: "Cinema Complex, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Cinema",
    price: 150,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 650,
    tags: ["Documentary", "Film Festival", "Cinema", "Culture"],
    featured: true,
    rating: 4.5,
  },
  {
    id: "20",
    title: "International Short Film Showcase",
    description:
      "A collection of award-winning short films from international filmmakers, showcasing diverse storytelling and innovative cinematography.",
    image: "/street-art-graffiti-workshop.jpg",
    hoverVideo: "/video/Make_a_video_202512011743_xo3sl.mp4",
    date: new Date("2025-03-22"),
    time: "05:30 PM",
    location: "Art Cinema Hall, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Cinema",
    price: 120,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 480,
    tags: ["Short Films", "International", "Cinema", "Showcase"],
    featured: true,
    rating: 4.6,
  },
  {
    id: "21",
    title: "Ollywood Film Premiere Night",
    description: "Exclusive premiere of the latest Odia blockbuster film with star cast meet and greet.",
    image: "https://www.mgientertainment.com/app/uploads/2018/04/Jennifer-Lawrence-The-Hunger-Games_-Catching-Fire-Hollywood-Premiere-06.jpg",
    date: new Date("2025-03-25"),
    time: "07:00 PM",
    location: "Cinepolis, Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Ollywood",
    price: 250,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 450,
    tags: ["Ollywood", "Film", "Premiere"],
    rating: 4.5,
  },
  {
    id: "22",
    title: "Ollywood Music Awards 2025",
    description: "Annual awards ceremony celebrating the best of Odia film music and artists.",
    image: "/concert-stage-lights-event.jpg",
    date: new Date("2025-04-05"),
    time: "06:30 PM",
    location: "Kalinga Stadium, Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Ollywood",
    price: 500,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 2500,
    tags: ["Ollywood", "Awards", "Music"],
    rating: 4.8,
  },
  {
    id: "23",
    title: "Ollywood Actor Workshop",
    description: "Learn acting techniques from renowned Ollywood actors in this intensive workshop.",
    image: "https://5.imimg.com/data5/LE/ND/GLADMIN-61309306/acting-workshop-services.png",
    date: new Date("2025-03-28"),
    time: "10:00 AM",
    location: "Film City, Cuttack, Odisha",
    city: "Cuttack",
    coordinates: { lat: 20.5, lng: 85.8 },
    category: "Ollywood",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 120,
    tags: ["Ollywood", "Workshop", "Acting"],
    rating: 4.6,
  },
  {
    id: "24",
    title: "Jollywood Film Festival",
    description: "Celebrate Jharkhand cinema with screenings of award-winning Jollywood films.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_ngXC3iyLqfe-ki7baPg0iMu5FLVhUkDixw&s",
    date: new Date("2025-04-10"),
    time: "05:00 PM",
    location: "Ranchi Film Hall, Ranchi, Jharkhand",
    city: "Ranchi",
    coordinates: { lat: 23.3441, lng: 85.3096 },
    category: "Jollywood",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 380,
    tags: ["Jollywood", "Film", "Festival"],
    rating: 4.4,
  },
  {
    id: "25",
    title: "Jollywood Star Night",
    description: "Meet your favorite Jollywood stars in this exclusive fan meet and entertainment night.",
    image: "https://disneyparksblog.com/app/uploads/2024/09/wdw-dhs-jollywood-nights-characters.jpg",
    date: new Date("2025-04-15"),
    time: "07:00 PM",
    location: "City Center, Ranchi, Jharkhand",
    city: "Ranchi",
    coordinates: { lat: 23.3441, lng: 85.3096 },
    category: "Jollywood",
    price: 300,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 650,
    tags: ["Jollywood", "Stars", "Entertainment"],
    rating: 4.7,
  },
  {
    id: "26",
    title: "Jollywood Filmmaking Workshop",
    description: "Learn the art of filmmaking from experienced Jollywood directors and cinematographers.",
    image: "https://www.aims.edu/sites/default/files/styles/16_9__1088x612/public/PVP%20Filming%20at%20Aims.jpg?itok=YKCZs5fI",
    date: new Date("2025-04-20"),
    time: "09:00 AM",
    location: "Media Institute, Ranchi, Jharkhand",
    city: "Ranchi",
    coordinates: { lat: 23.3441, lng: 85.3096 },
    category: "Jollywood",
    price: 400,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 95,
    tags: ["Jollywood", "Workshop", "Filmmaking"],
    rating: 4.5,
  },
  {
    id: "27",
    title: "Social Media Influencer Summit",
    description: "Connect with top influencers and learn strategies for growing your social media presence.",
    image: "/tech-conference-stage.jpg",
    date: new Date("2025-04-25"),
    time: "10:00 AM",
    location: "Convention Center, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Influencer",
    price: 599,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 1200,
    tags: ["Influencer", "Social Media", "Summit"],
    rating: 4.8,
  },
  {
    id: "28",
    title: "Influencer Meet & Greet",
    description: "Meet your favorite social media influencers in person and get exclusive content.",
    image: "https://media.gettyimages.com/id/693987340/photo/los-angeles-ca-guests-line-up-to-attend-the-meet-and-greet-hosted-by-top-beauty-influencer.jpg?s=612x612&w=0&k=20&c=U8zKrHD93AcHtKK_IqWR0kaoanscfZ0VTDA5Cwonjxc=",
    date: new Date("2025-05-01"),
    time: "04:00 PM",
    location: "Mall of India, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Influencer",
    price: 250,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 850,
    tags: ["Influencer", "Meet", "Social Media"],
    rating: 4.6,
  },
  {
    id: "29",
    title: "Content Creator Workshop",
    description: "Learn content creation tips and tricks from successful influencers and creators.",
    image: "/ai-machine-learning-classroom.jpg",
    date: new Date("2025-05-05"),
    time: "11:00 AM",
    location: "Digital Hub, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Influencer",
    price: 450,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 320,
    tags: ["Influencer", "Workshop", "Content"],
    rating: 4.7,
  },
  {
    id: "30",
    title: "Stand-Up Comedy Night",
    description: "Laugh out loud with top comedians performing their best stand-up routines.",
    image: "https://media.gettyimages.com/id/2187503831/photo/tattooed-comedian-brings-house-down-plus-size-latino-entertainer-performs-at-night-country.jpg?s=612x612&w=0&k=20&c=jsRfNc2z5mTOt00ZC_lvdBLAEEMaNn93S1IgJfHs6Hw=",
    date: new Date("2025-05-10"),
    time: "08:00 PM",
    location: "Comedy Club, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Comedian",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 420,
    tags: ["Comedy", "Stand-up", "Entertainment"],
    rating: 4.9,
  },
  {
    id: "31",
    title: "Comedy Festival 2025",
    description: "Three days of non-stop laughter with India's best comedians.",
    image: "/global-arts-summit-networking.jpg",
    date: new Date("2025-05-15"),
    time: "06:00 PM",
    location: "Open Air Theatre, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Comedian",
    price: 500,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 1500,
    tags: ["Comedy", "Festival", "Entertainment"],
    rating: 4.8,
  },
  {
    id: "32",
    title: "Open Mic Comedy Night",
    description: "Try your hand at stand-up comedy or watch aspiring comedians perform.",
    image: "https://media.gettyimages.com/id/622599318/photo/washington-dc-comedian-and-former-baltimore-cop-timmy-hall-performs-during-thursdays-open-mic.jpg?s=612x612&w=0&k=20&c=SuINF76Y1A74IWdJtAhlvBv4LKBCk2ntFpTDuT7cba4=",
    date: new Date("2025-05-20"),
    time: "07:30 PM",
    location: "Cafe Laughter, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Comedian",
    price: 150,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 180,
    tags: ["Comedy", "Open Mic", "Entertainment"],
    rating: 4.5,
  },
  {
    id: "33",
    title: "Cricket Championship Finals",
    description: "Watch the thrilling finals of the city cricket championship live.",
    image: "/esports-gaming-tournament.jpg",
    date: new Date("2025-05-25"),
    time: "02:00 PM",
    location: "Sports Stadium, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Sports",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 5000,
    tags: ["Sports", "Cricket", "Championship"],
    rating: 4.7,
  },
  {
    id: "34",
    title: "Marathon Run 2025",
    description: "Participate in the annual city marathon and promote fitness and health.",
    image: "/fitness-expo-event.jpg",
    date: new Date("2025-06-01"),
    time: "06:00 AM",
    location: "City Center, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Sports",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[3],
    attendees: 3500,
    tags: ["Sports", "Marathon", "Fitness"],
    rating: 4.8,
  },
  {
    id: "35",
    title: "ফুটবল টুর্নামেন্ট",
    description: "শীর্ষ স্থানীয় দলগুলির সাথে আন্তঃশহর ফুটবল টুর্নামেন্ট।",
    image: "https://media.gettyimages.com/id/474914003/photo/soccer-player-jumping-with-ball.jpg?s=612x612&w=0&k=20&c=7TGCj3xbKLSiZG0_MiUccqch8HrNrFu_wNApD9FUK78=",
    date: new Date("2025-06-05"),
    time: "বিকাল ৪:০০টা",
    location: "ফুটবল গ্রাউন্ড, কলকাতা, পশ্চিমবঙ্গ",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Sports",
    price: 100,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 2200,
    tags: ["খেলাধুলা", "ফুটবল", "টুর্নামেন্ট"],
    rating: 4.6,
  },
  {
    id: "36",
    title: "YouTuber Meetup 2025",
    description: "Meet popular YouTubers and learn about content creation and video production.",
    image: "https://www.tastyedits.com/wp-content/uploads/2022/12/blog-header-youtuber-events-2025.png",
    date: new Date("2025-06-10"),
    time: "03:00 PM",
    location: "Tech Park, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "YouTuber's",
    price: 300,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 950,
    tags: ["YouTube", "Content", "Meetup"],
    rating: 4.7,
  },
  {
    id: "37",
    title: "YouTube Creator Summit",
    description: "Learn monetization strategies and growth hacks from successful YouTubers.",
    image: "/startup-pitch-event.png",
    date: new Date("2025-06-15"),
    time: "10:00 AM",
    location: "Convention Hall, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "YouTuber's",
    price: 550,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 1400,
    tags: ["YouTube", "Summit", "Creator"],
    rating: 4.8,
  },
  {
    id: "38",
    title: "Video Editing Workshop by YouTubers",
    description: "Master video editing techniques from professional YouTubers.",
    image: "https://cdn.prod.website-files.com/662b8a4944dbb4e0ccd51a28/677f9f84f330fb764733f95a_66fd5577c926622784e9eb1e_best%2520video%2520editin%2520course.png",
    date: new Date("2025-06-20"),
    time: "11:00 AM",
    location: "Media Lab, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "YouTuber's",
    price: 400,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 280,
    tags: ["YouTube", "Workshop", "Editing"],
    rating: 4.6,
  },
  {
    id: "39",
    title: "Contemporary Dance Performance",
    description: "Experience stunning contemporary dance performances by professional dancers.",
    image: "https://artsequator.s3.ap-southeast-1.amazonaws.com/2022/03/Chowk_PallaviinTime_Esplanade.jpg",
    date: new Date("2025-06-25"),
    time: "07:00 PM",
    location: "Dance Theatre, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Dancer",
    price: 280,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 520,
    tags: ["Dance", "Contemporary", "Performance"],
    rating: 4.7,
  },
  {
    id: "40",
    title: "Hip Hop Dance Battle",
    description: "Watch the best hip hop dancers compete in this high-energy dance battle.",
    image: "https://img.redbull.com/images/c_crop,w_3200,h_1600,x_0,y_360/c_auto,w_1200,h_630/f_auto,q_auto/redbullcom/2018/05/07/7dd771ad-f327-40bf-9c81-b679d4a85b64/juste-debout-2018-diablo-stalamuerte",
    date: new Date("2025-07-01"),
    time: "06:00 PM",
    location: "Street Arena, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Dancer",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 680,
    tags: ["Dance", "Hip Hop", "Battle"],
    rating: 4.8,
  },
  {
    id: "41",
    title: "Dance Workshop for Beginners",
    description: "Learn various dance styles from professional dancers in this beginner-friendly workshop.",
    image: "https://media.gettyimages.com/id/1241867199/photo/in-this-photo-taken-on-july-2-korean-american-k-pop-star-alexa-who-recently-won-the-american.jpg?s=612x612&w=0&k=20&c=dLO7FYSgbtgZ05v9139rNgzODd1UiQV0BKF14ebNHU0=",
    date: new Date("2025-07-05"),
    time: "10:00 AM",
    location: "Dance Studio, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Dancer",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 145,
    tags: ["Dance", "Workshop", "Beginners"],
    rating: 4.5,
  },
  {
    id: "42",
    title: "Book Launch & Author Meet",
    description: "Meet bestselling authors and get your books signed at this exclusive book launch event.",
    image: "https://media.gettyimages.com/id/96438325/photo/bologna-italy-writer-james-ellroy-meet-italian-writer-carlo-lucarelli-for-the-book-launch.jpg?s=612x612&w=0&k=20&c=ySAi6LTYMOgP2FsPKDq3-UjjCN_1GV04faug7CILuIU=",
    date: new Date("2025-07-10"),
    time: "05:00 PM",
    location: "Literary Hall, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Authors",
    price: 150,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 380,
    tags: ["Books", "Authors", "Literature"],
    rating: 4.6,
  },
  {
    id: "43",
    title: "Writers Workshop",
    description: "Learn creative writing techniques from award-winning authors.",
    image: "https://static1.squarespace.com/static/53483788e4b04a5110f40b43/53485aafe4b03733717b20a2/53485ac3e4b03733717b2330/1397250773737/?format=1500w",
    date: new Date("2025-07-15"),
    time: "11:00 AM",
    location: "Library Hall, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Authors",
    price: 400,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 220,
    tags: ["Writing", "Workshop", "Authors"],
    rating: 4.7,
  },
  {
    id: "44",
    title: "Literary Festival 2025",
    description: "Celebrate literature with panel discussions, book readings, and author interactions.",
    image: "https://media.gettyimages.com/id/2156680226/photo/london-england-vicki-perrin-the-queens-reading-room-literary-festival-ceo-speaks-to-the.jpg?s=612x612&w=0&k=20&c=m_BCCKfpdTlxnjWEdMRzS5kSYyOyR5P8vFgihezS8pc=",
    date: new Date("2025-07-20"),
    time: "09:00 AM",
    location: "Cultural Center, Kolkata, West Bengal",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Authors",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[2],
    attendees: 1200,
    tags: ["Literature", "Festival", "Authors"],
    rating: 4.8,
  },

  {
    id: "46",
    title: "Open Mic Poetry Night",
    description: "Share your poetry or listen to beautiful verses in this open mic poetry session.",
    image: "https://www.thersa.org/wp-content/uploads/2025/02/PoetryOpenMic-Listing_Image-optimised.png",
    date: new Date("2025-08-01"),
    time: "08:00 PM",
    location: "Poetry Corner, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Poet",
    price: 50,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 180,
    tags: ["Poetry", "Open Mic", "Literature"],
    rating: 4.5,
  },
  {
    id: "47",
    title: "Poetry Workshop with Renowned Poets",
    description: "Learn the art of poetry writing from celebrated poets.",
    image: "https://www.napawritersconference.org/wp-content/uploads/2019/01/Napa-Valley-Writers-Conference-craft-of-writing-poetry-fiction-translation_workshops2.jpg",
    date: new Date("2025-08-05"),
    time: "10:00 AM",
    location: "Writers Hub, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Poet",
    price: 300,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 95,
    tags: ["Poetry", "Workshop", "Writing"],
    rating: 4.7,
  },

  {
    id: "49",
    title: "Sunny Hindustani",
    description: "A rising star from Indian Idol with exceptional vocal range and stage presence. Known for his versatile singing style and ability to connect with audiences through his performances.",
    image: "/placeholder-user.jpg",
    date: new Date("2025-02-01"),
    time: "04:00 PM",
    location: "Mall Plaza, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Indian idol Artist",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 720,
    tags: ["Indian Idol", "Star", "Sunny Hindustani"],
    featured: true,
    rating: 4.9,
  },
  {
    id: "50",
    title: "Salman Ali",
    description: "Indian Idol Season 10 winner and renowned playback singer. Known for his melodious voice and versatile singing across various genres including classical, Bollywood, and folk music.",
    image: "/placeholder-user.jpg",
    date: new Date("2025-02-02"),
    time: "11:00 AM",
    location: "Music Academy, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Indian idol Artist",
    price: 450,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 185,
    tags: ["Indian Idol", "Winner", "Salman Ali"],
    featured: true,
    rating: 4.8,
  },
  {
    id: "51",
    title: "Theatre Play - Modern Drama",
    description: "Experience powerful storytelling through this contemporary theatre production.",
    image: "https://i.pinimg.com/736x/46/39/79/463979f4309a303a121ec4f0e91ecc5a.jpg",
    date: new Date("2025-08-25"),
    time: "07:30 PM",
    location: "Theatre House, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Theatre Artists",
    price: 250,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 420,
    tags: ["Theatre", "Drama", "Performance"],
    rating: 4.6,
  },
  {
    id: "52",
    title: "Street Theatre Festival",
    description: "Watch engaging street theatre performances addressing social issues.",
    image: "https://artculturefestival.in/wp-content/uploads/2025/06/image.jpeg",
    date: new Date("2025-09-01"),
    time: "06:00 PM",
    location: "City Square, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Theatre Artists",
    price: 0,
    isFree: true,
    isOnline: false,
    organizer: organizers[2],
    attendees: 850,
    tags: ["Theatre", "Street", "Festival"],
    rating: 4.7,
  },
  {
    id: "53",
    title: "Acting Workshop by Theatre Artists",
    description: "Learn acting skills from experienced theatre artists in this hands-on workshop.",
    image: "https://assets-in.bmscdn.com/discovery-catalog/events/et00473634-jxvlyqjvqb-landscape.jpg",
    date: new Date("2025-09-05"),
    time: "10:00 AM",
    location: "Drama School, Kolkata, West Bengal",
    city: "Kolkata",
    coordinates: { lat: 22.5726, lng: 88.3639 },
    category: "Theatre Artists",
    price: 380,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 165,
    tags: ["Theatre", "Workshop", "Acting"],
    rating: 4.8,
  },
  {
    id: "54",
    title: "Classical Instrumental Concert",
    description: "Enjoy mesmerizing performances by master instrumentalists playing classical music.",
    image: "https://media.gettyimages.com/id/2236105656/photo/elegant-quartet-performing-on-stage-with-graceful-violinist-and-string-instruments.jpg?s=612x612&w=0&k=20&c=9K7YUG_avAaohnuuFBec4MWtY9QXhUQjTXoSX_hRndc=",
    date: new Date("2025-09-10"),
    time: "07:00 PM",
    location: "Music Hall, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Instrumentalist",
    price: 400,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 680,
    tags: ["Instrumental", "Classical", "Concert"],
    rating: 4.9,
  },
  {
    id: "55",
    title: "Guitar Workshop by Professional Musicians",
    description: "Learn guitar techniques from professional instrumentalists.",
    image: "https://media.gettyimages.com/id/1951039111/photo/mexico-city-mexico-students-attend-a-mariachi-music-class-at-the-mariachi-school-ollin.jpg?s=612x612&w=0&k=20&c=J-0l5dwznPv8W1O4UHX8yNTaQSfJL4u6k3wpuUDcwrk=",
    date: new Date("2025-09-15"),
    time: "11:00 AM",
    location: "Music Institute, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Instrumentalist",
    price: 500,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 140,
    tags: ["Instrumental", "Guitar", "Workshop"],
    rating: 4.7,
  },
  {
    id: "56",
    title: "Fusion Music Night",
    description: "Experience the blend of traditional and modern music by talented instrumentalists.",
    image: "https://media.gettyimages.com/id/457609550/photo/dancing-with-the-stars-episode-1906-international-superstar-pitbull-returned-to-the-ballroom.jpg?s=612x612&w=0&k=20&c=vLaVzYNiygXoBvcPazWXPdVsJIw6qmpTQVbsCyJPZg4=",
    date: new Date("2025-09-20"),
    time: "08:00 PM",
    location: "Amphitheatre, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Instrumentalist",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 920,
    tags: ["Instrumental", "Fusion", "Music"],
    rating: 4.8,
  },
  {
    id: "57",
    title: "Magic Show Extravaganza",
    description: "Be amazed by mind-blowing magic tricks and illusions by professional magicians.",
    image: "https://theinsightwire.in/wp-content/uploads/2025/12/171569-1024x768.jpg",
    date: new Date("2025-09-25"),
    time: "06:30 PM",
    location: "Magic Theatre, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Magician",
    price: 300,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 550,
    tags: ["Magic", "Show", "Entertainment"],
    rating: 4.8,
  },
  {
    id: "58",
    title: "Kids Magic Workshop",
    description: "Learn simple magic tricks in this fun workshop designed for children.",
    image: "https://ajmagicshow.com.au/wp-content/uploads/kids-magician-5.png.webp",
    date: new Date("2025-10-01"),
    time: "03:00 PM",
    location: "Community Center, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Magician",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 280,
    tags: ["Magic", "Workshop", "Kids"],
    rating: 4.6,
  },
  {
    id: "59",
    title: "International Magic Festival",
    description: "Watch world-class magicians perform incredible illusions and magic acts.",
    image: "https://media.gettyimages.com/id/614254252/photo/magician-performing-at-the-annual-international-art-of-storytelling-family-festival.jpg?s=612x612&w=0&k=20&c=tXIDArK3Yv84VGf63YEs6YKTmP2RrGOb9inL1i2cmDU=",
    date: new Date("2025-10-05"),
    time: "07:00 PM",
    location: "Grand Theatre, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Magician",
    price: 450,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 1200,
    tags: ["Magic", "Festival", "International"],
    rating: 4.9,
  },
  {
    id: "60",
    title: "RJ Meet & Greet",
    description: "Meet your favorite radio jockeys and learn about the world of radio broadcasting.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYHmjmp8xQeSem_XeJ_YOpjef03iNRp0tJsg&s",
    date: new Date("2025-10-10"),
    time: "05:00 PM",
    location: "Radio Station, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "RJ",
    price: 150,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 320,
    tags: ["RJ", "Radio", "Meet"],
    rating: 4.5,
  },
  {
    id: "61",
    title: "Radio Jockey Workshop",
    description: "Learn voice modulation, anchoring, and broadcasting skills from professional RJs.",
    image: "https://aaft.com/blog/wp-content/uploads/2024/07/2148815422.jpg",
    date: new Date("2025-10-15"),
    time: "10:00 AM",
    location: "Media Institute, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "RJ",
    price: 400,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 175,
    tags: ["RJ", "Workshop", "Broadcasting"],
    rating: 4.7,
  },
  {
    id: "62",
    title: "Live Radio Show Recording",
    description: "Be part of a live radio show recording with popular RJs and celebrity guests.",
    image: "https://media.gettyimages.com/id/1490180890/photo/group-of-people-in-a-live-podcast-show.jpg?s=612x612&w=0&k=20&c=PBQ9o7JAktEwKJfg7hp2mh5gKoFKSkV_BFrplD3B13A=",
    date: new Date("2025-10-20"),
    time: "06:00 PM",
    location: "Studio Theatre, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "RJ",
    price: 250,
    isFree: false,
    isOnline: false,
    organizer: organizers[3],
    attendees: 480,
    tags: ["RJ", "Radio", "Live Show"],
    rating: 4.8,
  },
  {
    id: "63",
    title: "Indian Idol Artist Performance",
    description: "Experience live performances by talented Indian Idol artists showcasing their musical journey.",
    image: "https://media.gettyimages.com/id/897312902/photo/tamil-bharatnatyam-dancer-performs-an-expressive-dance-during-her-arangetram-in-brampton.jpg?s=612x612&w=0&k=20&c=1_fjQ-J8Uc8-tsZjjQNesZb_PREwDaF-fWxC_7ao2Qk=",
    date: new Date("2025-11-01"),
    time: "07:00 PM",
    location: "Music Arena, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Music",
    price: 450,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 1800,
    tags: ["Indian Idol", "Artist", "Live"],
    rating: 4.8,
  },
  {
    id: "64",
    title: "Indian Idol Artist Music Workshop",
    description: "Learn singing techniques and music composition from professional Indian Idol artists.",
    image: "https://content.jdmagicbox.com/v2/comp/mumbai/m7/022pxx22.xx22.160221123014.e5m7/catalogue/indian-idol-academy-andheri-west-mumbai-music-classes-jh3ln.jpg",
    date: new Date("2025-11-05"),
    time: "11:00 AM",
    location: "Music Institute, Delhi, India",
    city: "Delhi",
    coordinates: { lat: 28.7041, lng: 77.1025 },
    category: "Music",
    price: 350,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 220,
    tags: ["Indian Idol", "Workshop", "Music"],
    rating: 4.7,
  },
  {
    id: "65",
    title: "Indian Idol Artist Fan Meet",
    description: "Meet your favorite Indian Idol artists, get autographs and take photos in this exclusive fan event.",
    image: "https://images.filmibeat.com/img/2018/11/indian-idol-3-1543495300.jpg",
    date: new Date("2025-11-10"),
    time: "04:00 PM",
    location: "Convention Center, Bangalore, Karnataka",
    city: "Bangalore",
    coordinates: { lat: 12.9716, lng: 77.5946 },
    category: "Music",
    price: 200,
    isFree: false,
    isOnline: false,
    organizer: organizers[2],
    attendees: 950,
    tags: ["Indian Idol", "Fan Meet", "Artist"],
    rating: 4.9,
  },
  {
    id: "66",
    title: "Sunny Hindustani Live Concert",
    description: "Experience the magic of Sunny Hindustani's voice in this exclusive live concert featuring his best performances from Indian Idol.",
    image: "https://www.tribuneindia.com/sortd-service/imaginary/v22-01/jpg/large/high?url=dGhldHJpYnVuZS1zb3J0ZC1wcm8tcHJvZC1zb3J0ZC9tZWRpYTY0NjA4ZTMwLTRlN2UtMTFlZi1iY2VhLWU1MDI2ZDljNzJmMi5qcGc=",
    date: new Date("2025-11-12"),
    time: "08:00 PM",
    location: "Kalinga Stadium, Bhubaneswar, Odisha",
    city: "Bhubaneswar",
    coordinates: { lat: 20.2961, lng: 85.8245 },
    category: "Music",
    price: 599,
    isFree: false,
    isOnline: false,
    organizer: organizers[0],
    attendees: 2500,
    tags: ["Sunny Hindustani", "Indian Idol", "Concert"],
    rating: 4.9,
  },
  {
    id: "67",
    title: "Salman Ali Musical Evening",
    description: "Join Indian Idol winner Salman Ali for an enchanting musical evening featuring classical and Bollywood hits.",
    image: "https://www.pickeronline.com/uploads/bussiness/2019/01//15475364755c3d885b97289.png",
    date: new Date("2025-11-18"),
    time: "07:30 PM",
    location: "Music Academy, Mumbai, Maharashtra",
    city: "Mumbai",
    coordinates: { lat: 19.076, lng: 72.8777 },
    category: "Music",
    price: 750,
    isFree: false,
    isOnline: false,
    organizer: organizers[1],
    attendees: 1200,
    tags: ["Salman Ali", "Indian Idol", "Winner"],
    rating: 4.8,
  },
]

// Function to get translated events based on language
export function getTranslatedEvents(language: string = 'en'): Event[] {
  if (language !== 'bn') return mockEvents
  
  return mockEvents.map(event => ({
    ...event,
    time: translateEventTime(event.time, language),
    location: translateEventLocation(event.location, language),
    tags: translateEventTags(event.tags, language)
  }))
}
